### ISSUE TITLE
Accessors chain and inheritance

### ISSUE THREAD

**Issue by DSEyers** [projectlombok/lombok#2843] opened 2021-05-14 17:37 UTC
**Scenario**
Was expecting if use ancessor chaining that on child I could set child instances variables and parent, but only way is to first do all child settings (makes sense). but not ideal.

```
@Accessors(chain = true)
public class Parent {
    private String nameParent;
}
```

```
@Accessors(chain = true)
public class Child extends Parent {
    private String nameChild;
}
```

Then try to use the setters on a child once you have used a parent setter you can not access other child setters.
 public static void main(String[] args) {
        final Child child1 = new Child()
                .setNameParent("parent")
                .setNameChild("child");   // This you can NOT do (it returned parent object prior)

        final Child child2 = new Child()
                .setNameChild("child") 
                .setNameParent("parent");  // works
    }

**Comment by janrieke** [comment] 2021-05-14 19:22
Java does not have a concept like a SELF return type. You can emulate it using type parameters, but it's quite ugly and has some problems. There has been a discussion whether Lombok could generate such code, but it did not cross the line where the usefulness outweighs the maintenance burden (see #1147).

**Comment by craftmaster2190** [comment] 2022-01-18 22:48
+1

**Comment by rzwitserloot** [comment] 2022-01-19 00:12
Duplicate of #3034

**Closed by rzwitserloot** 2022-01-19 00:12 UTC

**Comment by rzwitserloot** [comment] 2022-01-19 02:24
Duplicate of #1147
