### ISSUE TITLE
@Default does not work for values that are also lombok builders

### ISSUE THREAD

**Issue by paulwinters** [projectlombok/lombok#1452] opened 2017-08-09 21:21 UTC
For a class with the `@Builder` annotation, I am using the `@Default` for each of its global fields. The fields that are using lombok annotations are always coming back as null where fields that are using non lombok code are being set correctly. 

```
public class LombokDefaultTest {
    public static void main(String... args) {
        System.out.println("Starting");

        SoftAssert softAssert = new SoftAssert();
        InnerA innerA1 = InnerA.builder().build();

        softAssert.assertNull(innerA1.getA(), "innerA1.getA() should be null. Is[" + innerA1.getA() + "]");
        softAssert.assertNull(innerA1.getB(), "innerA1.getB() should be null. Is[" + innerA1.getB() + "]");

        InnerA innerA2 = InnerA.builder().a("foo").b("bar").build();

        softAssert.assertNotNull(innerA2.getA(), "innerA2.getA() should not be null");
        softAssert.assertNotNull(innerA2.getB(), "innerA2.getB() should not be null");

        InnerB innerB1 = InnerB.builder().build();

        softAssert.assertNotNull(innerB1.getMaps(), "innerB1.getMaps() should not be null");
        softAssert.assertNotNull(innerB1.getLists(), "innerB1.getLists() should not be null");

        OuterA outerA = OuterA.builder().build();
        softAssert.assertNotNull(outerA.getInnerA(), "outerA.getInnerA() should not be null");
        softAssert.assertNotNull(outerA.getInnerB(), "outerA.getInnerB() should not be null");
        softAssert.assertNotNull(outerA.getLists(), "outerA.getLists() should not be null");

        OuterB outerB = OuterB.builder().build();

        softAssert.assertNotNull(outerB.getInnerA(), "outerB.getInnerA() should not be null");
        softAssert.assertNotNull(outerB.getInnerB(), "outerB.getInnerB() should not be null");
        softAssert.assertNotNull(outerB.getLists(), "outerB.getLists() should not be null");

        softAssert.assertAll();

        System.out.println("Finished");
    }
}

@AllArgsConstructor
@Builder
class OuterA {
    @Getter
    @Default
    private InnerA innerA = InnerA.builder().build();
    @Getter
    @Default
    private InnerB innerB = InnerB.builder().build();
    @Getter
    @Singular
    @Default
    private ImmutableList<String> lists = ImmutableList.<String> of();
}

@AllArgsConstructor
@Builder
class OuterB {
    @Getter
    @Default
    private InnerA innerA = new InnerA("foo", "bar");
    @Getter
    @Default
    private InnerB innerB = new InnerB(ImmutableMap.of(), ImmutableSet.<String> of());
    @Getter
    @Singular
    @Default
    private ImmutableList<String> lists = ImmutableList.<String> of();
}

@AllArgsConstructor
@Builder
class InnerA {
    @Getter
    private String a;
    @Getter
    private String b;
}

@AllArgsConstructor
@Builder
class InnerB {
    @Getter
    @Singular
    @Default
    private ImmutableMap<String, String> maps = ImmutableMap.of();
    @Getter
    @Singular
    @Default
    private ImmutableSet<String> lists = ImmutableSet.of();
}
```

Test Output
```
Starting
Exception in thread "main" java.lang.AssertionError: The following asserts failed:
	outerA.getInnerA() should not be null expected object to not be null,
	outerA.getInnerB() should not be null expected object to not be null,
	outerB.getInnerA() should not be null expected object to not be null,
	outerB.getInnerB() should not be null expected object to not be null
```

**Comment by robelcik** [comment] 2017-08-10 08:22
Hello!

Here is a simplified example:
``
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
class MyClass {
    @Builder.Default
    private int property = 5;
}

MyClass myObject1 = MyClass.builder().build();
System.out.println(myObject1.getProperty()); // --> 5, OK

MyClass myObject2 = new MyClass();
System.out.println(myObject2.getProperty()); // --> 0, not OK, 5 expected
``

**Comment by paulwinters** [comment] 2017-08-10 15:33
Simple work around if anyone else is having this problem is to set the default values in the inner class instead. 

```@AllArgsConstructor
@Builder
class OuterA {
    @Getter
    // @Default
    private InnerA innerA;
    @Getter
    // @Default
    private InnerB innerB;
    @Getter
    @Singular
    @Default
    private ImmutableList<String> lists = ImmutableList.<String> of();

    static class OuterABuilder {
        private InnerA innerA = InnerA.builder().build();
        private InnerB innerB = InnerB.builder().build();
    }
}
```

**Comment by kevcodez** [comment] 2017-08-15 07:42
See https://github.com/rzwitserloot/lombok/issues/1347

**Comment by w3blogfr** [comment] 2021-02-12 16:19
See also #2340

**Comment by Rawi01** [comment] 2024-03-12 23:12
Duplicate of #2340

**Closed by Rawi01** 2024-03-12 23:12 UTC
