### ISSUE TITLE
[BUG] Lombok ignores lombok.config

### ISSUE THREAD

**Issue by snjeza** [projectlombok/lombok#3406] opened 2023-04-15 17:01 UTC
Related issues:
- https://github.com/redhat-developer/vscode-java/issues/2887#issuecomment-1509888278
- https://github.com/projectlombok/lombok/issues/3332
Steps to reproduce:
- install eclipse 4.27+
- install m2e
- import project [vscode-java-issue](https://github.com/redhat-developer/vscode-java/files/10441007/vscode-java-issue.zip)
- close all editors
- restart eclipse
- call Project>Clean...
You will get `LOG cannot be resolved`.

A workaround

- open Test.java
- restart Eclipse

**Comment by rspilker** [comment] 2023-04-15 20:52
Did you try the [edge release](https://projectlombok.org/download-edge)? This sounds like a duplicate of #3332

**Comment by snjeza** [comment] 2023-04-15 21:10
I have created [lombok-20230415](https://github.com/snjeza/vscode-test/raw/master/lombok-20230415.jar) using the [lombok ](https://github.com/projectlombok/lombok) master branch. It can also be reproduced using the edge release.
The issue is similar to #3332, but not the same. See `A workaround` above.

**Comment by Rawi01** [comment] 2023-04-16 09:33
Can reproduce this and working on a fix

**Comment by Rawi01** [comment] 2023-04-16 11:24
@snjeza Can you try if my fix (https://github.com/Rawi01/lombok/suites/12266357878/artifacts/649504284) also works for you?

**Comment by snjeza** [comment] 2023-04-16 12:58
@Rawi01 It works.

**Closed** 2023-04-16 16:10 UTC

**Comment by snjeza** [comment] 2023-04-16 16:20
@rspilker @Rawi01 Could you, please, update [edge release](https://projectlombok.org/download-edge) ?

**Comment by rspilker** [comment] 2023-04-16 23:35
Yes, it has just been released

**Comment by mxmlnglt** [comment] 2023-05-09 15:06
> Yes, it has just been released

Note however #3414.
