### ISSUE TITLE
[BUG] NPE when invoking a method on a val variable

### ISSUE THREAD

**Issue by kdurnoga** [projectlombok/lombok#2460] opened 2020-05-11 21:17 UTC
**Describe the bug**
Javac crashes with a `NullPointerException` on code that contains method invocation on a variable declared with `val` if the invocation is wrapped with extra parentheses (cf. the snippet below). The error message reads: 
```
Information:java: compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.6, {1}, {2}, {3}, {4}, {5}, {6}, {7}
Information:java: java.lang.NullPointerException
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1235)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1634)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:398)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.visitExec(TreeScanner.java:213)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1452)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitBlock(Flow.java:997)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1020)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitMethodDef(Flow.java:964)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:927)
Information:java: 	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1327)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1317)
Information:java: 	at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:218)
Information:java: 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1401)
Information:java: 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
Information:java: 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
Information:java: 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
Information:java: 	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:207)
```

**To Reproduce**
Compile the following snippet:
```java
import lombok.val;

public class Test {
	public static void main(String[] args) {
		val x = "a";
		System.out.println((x.equals("b")));
	}
}
```
Note the extra parentheses around the `equals` invocation. The result should be passed as an argument to another method.

**Expected behavior**
The compiler should not crash. Removing the spare parentheses fixes the problem and the code compiles fine. (Obviously, it also does so when `val` is replaced with `String` or `var`.)

**Version info (please complete the following information):**
 - Lombok 1.18.8 or 1.18.12
 - JBR 11 (bundled with IntelliJ 2020.1) with javac 11.0.6; I'm pretty sure I've observed the same behavior on AdoptOpenJDK's JDK 11 and Oracle's JDK 14

**Comment by Rawi01** [comment] 2020-05-13 22:31
Can confirm that it doesn't work using Java 14. It works without any problems using Java 8. 

During debugging I noticed that the value set in the `if` path of this snippet
https://github.com/rzwitserloot/lombok/blob/d54b360af9bdd66885badb80007d6839ea9d48f8/src/core/lombok/javac/handlers/HandleVal.java#L118-L122
breaks type resoultion which leads to this error. Simply using the `else` path works. I'm quite sure that this stuff is there for a reason and simply removing it will break other things...

**Comment by rspilker** [comment] 2020-05-14 19:03
Yes, the problem is that later java versions do more "target typing"

In short, this using target typing, binding of the types of parameters or return types depends on the type of the variable it is assigned to. 

Since the older compilers didn't care, we could just use `java.lang.Object`.

For the newer compilers, we use a non-existing type. The compiler should be able to handle that, since types could be created by an annotation processor in a later stage.

Possibly, the fix here is to make those non-existing types unique by adding a suffix (counter or random string).

**Comment by Rawi01** [comment] 2020-05-15 14:15
The type resolution for this example works properly, `val` gets replaced by `final java.lang.String` later in this handler. The created structure is exactly the same as the structure generated using `final java.lang.String` directly. The dummy type is not present anymore but gets set during the regular attribution stage. I guess that there is some kind of cache that gets polluted during type resolution, most likely one of the fields defined in `Context` but thats really hard to debug.

**Closed** 2021-06-03 16:36 UTC
