### ISSUE TITLE
Add PropertyChangeSupport to @Data for two-way databinding

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#100] opened 2015-07-14 19:15 UTC
_Migrated from Google Code (issue 27)_

**Comment by rzwitserloot** [comment] 2021-09-14 11:52
I'm closing this, with pain in my heart.

The problem is: The 'obvious' ways to do this, which somewhat match what the community does, are, in my opinion, bad. Possibly not their fault, given that they don't have code gen in their tool box.

I do not want to introduce a feature in lombok when I _know_ a better take is realistic.

Nevertheless, this feature clearly isn't important enough: GUIs with java aren't exactly popular. Perhaps a self-fulfilling prophecy (GUI building in java is not popular and insofar that people do it, they don't use the notion of binding properties/fields to a widget as the way to make it happen, _because_ it's hard to set it up), but it does mean that in order to change the world, we need to be out there advocating for this newer, better way.

If the community at large is clearly shrieking out for a fix, I could be tempted in getting the soapbox out. But the 'build GUIs in java' community seems hard to reach and somewhat conservative to me: That plan seems clearly doomed to failure for me.

Which leaves us with no options. I won't accept a crappy take on properties, and a good take probably won't be understood / adopted by the community.

**Closed by rzwitserloot** 2021-09-14 11:52 UTC
Labels: enhancement, accepted
