### ISSUE TITLE
LOMBOK eclipse isntall repository cannot be accessed

### ISSUE THREAD

**Issue by costin3141** [projectlombok/lombok#3184] opened 2022-04-28 07:36 UTC
Windows 10, latest updated, JDK 17. Latest Eclipse.

Adding https://projectlombok.org/p2 via install new software fails with the message:

Unable to read repository at https://projectlombok.org/p2/content.xml.
Unable to read repository at https://projectlombok.org/p2/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This happens with and without our vpn. Other update sites work fine.
Trying the url in an browser gives access forbidden.

**Comment by costin3141** [comment] 2022-04-28 08:18
Now installed jdk 18 and still got the issue.

**Comment by rzwitserloot** [comment] 2022-04-28 09:05
Duplicate of #3183 There is no need to create new issues.

**Closed by rzwitserloot** 2022-04-28 09:05 UTC
