### ISSUE TITLE
[BUG] lombok.fieldDefaults.defaultPrivate with records results in "@FieldDefaults is only supported on a class or an enum"

### ISSUE THREAD

**Issue by kanimaru** [projectlombok/lombok#3094] opened 2022-01-24 15:56 UTC
**Describe the bug**
When you use Java 14 records and also the configuration that every field is default private you can't compile the code. Cause the Intellij build process aborts with this error `java: @FieldDefaults is only supported on a class or an enum.`

**To Reproduce**
lombok.config with:
`lombok.fieldDefaults.defaultPrivate=true`

a record with:
`public record SomeRecord(String identifier) {}`

`javac -cp lombok-1.18.22.jar SomeRecord.java`

Result:
```
SomeRecord.java:6: error: @FieldDefaults is only supported on a class or an enum.
public record SomeRecord(String identifier) {
       ^
1 error
```

**Expected behavior**
It should compile :)

**Version info (please complete the following information):**
 - Lombok 1.18.22 from https://mvnrepository.com/artifact/org.projectlombok/lombok
 - Intellij Build #IU-213.6461.79, built on December 28, 2021
 - javac 17.0.1 / openjdk version "17.0.1" 2021-10-19

**Comment by Rawi01** [comment] 2022-01-24 19:07
Duplicate of #2995 and fixed in the [current edge version](https://projectlombok.org/download-edge)

**Closed by Rawi01** 2022-01-24 19:07 UTC
