### ISSUE TITLE
[BUG] lombok.Singular fails under JDK 19ea build 26

### ISSUE THREAD

**Issue by estekhin** [projectlombok/lombok#3211] opened 2022-06-14 10:47 UTC
**Describe the bug**
Using `lombok.Singular` causes `javac` from JDK 19ea build 26 to fail with
```
java.lang.ClassCastException: class com.sun.tools.javac.tree.JCTree$JCLiteral cannot be cast to class com.sun.tools.javac.tree.JCTree$JCCaseLabel (com.sun.tools.javac.tree.JCTree$JCLiteral and com.sun.tools.javac.tree.JCTree$JCCaseLabel are in module jdk.compiler of loader 'app')
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1932)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1932)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.handleSwitch(Attr.java:1692)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitSwitch(Attr.java:1604)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1287)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:687)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:761)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStats(Attr.java:780)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1463)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1082)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:687)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:761)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1253)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:912)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:687)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:761)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5621)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5512)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5336)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitClassDef(Attr.java:995)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:810)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:687)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:761)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5621)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5512)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5336)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:5275)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1317)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
```

**To Reproduce**
Compile the following code using JDK 19ea build 26:
```java
import java.util.List;

import lombok.Builder;
import lombok.Singular;
import lombok.Value;

@Value
@Builder
public class LombokValueWithBuilderAndSingularOverCollectionField {

    @Singular
    List<String> items;

}
```

**Expected behavior**
Compilation should be successful.

**Version info (please complete the following information):**
Lombok 1.18.24
JDK 19ea build 26

**Additional context**
The example code compiles successfully under JDK 19ea build 25 and earlier builds.

JDK 19ea build 26 contains https://bugs.openjdk.org/browse/JDK-8287236 and related commit https://github.com/openjdk/jdk/commit/bde7a7ae03f51360227c9757b2ab3ddbff4df908, where the hierarchy of `JCTree` subclasses has been changed, in particular `JCExpression` is a direct subclass of `JCTree` instead of being a subclass of `JCCaseLabel`. 

The handlers for `lombok.Singular` in https://github.com/projectlombok/lombok/tree/master/src/core/lombok/javac/handlers/singulars generate a `switch` statement with `JCLiteral` cases for `0` and `1` ints.
It seems that after https://github.com/openjdk/jdk/commit/bde7a7ae03f51360227c9757b2ab3ddbff4df908 that code should use `JCConstantCaseLabel` with `JCLiteral` inside.

I am not sure if supporting pre-JDK19 and JDK19-and-after variants of `switch` AST at the same time is feasible, so maybe the handlers for `lombok.Singular` should be refactored to use a sequence of "plain" `if` blocks to be more future-proof with regard to changes to `switch` statement in future JDK releases.

**Comment by Rawi01** [comment] 2022-06-14 20:02
Thanks for reporting this. It is no problem for lombok to support different ASTs, we already do that.

**Comment by cpotter1** [comment] 2022-07-21 14:35
any updates on this issue?

**Comment by MattiasSandelin** [comment] 2022-09-22 05:34
Do you have any release planned in order to get this fix to the maven repository etc? Thanks

**Comment by rzwitserloot** [comment] 2023-01-11 21:51
Duplicate of #3264 - this issue is older, but 3264 more generally describes the issue (which is, to put it simply, 'support JDK19 plz').

**Closed by rzwitserloot** 2023-01-11 21:51 UTC
Labels: bug, javac
