### ISSUE TITLE
[ENHANCEMENT] @ExtensionMethod with method reference

### ISSUE THREAD

**Issue by PhoenixmitX** [projectlombok/lombok#3227] opened 2022-07-07 08:16 UTC
**Describe the feature**
A clear and concise description of what the feature request/enhancement is. What is the goal of adding this feature request?
```java
@ExtensionMethod({LombokExtensionMethodWithMethodReference.Extensions.class})
public class LombokExtensionMethodWithMethodReference {

  public void methodReferenceWithExtensionMethod() {
    String foo = "foo";
    Optional<String> barOptional = Optional.of("bar");
    // compile error
    // Optional<String> fooBar = barOptional.map(foo::append);

    // workaround without method reference
    Optional<String> fooBar = barOptional.map(bar -> foo.append(bar));

    // both compiles to
    // Optional<String> fooBar = barOptional.map(bar -> Extensions.append(foo, bar));
  }
  
  @UtilityClass
  public static class Extensions {

   public String append(String s, String s2) {
      return s + s2;
   }
  }
}
```

My personal opinion is that the workaround looks ugly.
On top of this static code analyzer like sonar will detect this as code smell: 
`Replace this lambda with method reference 'foo::append'.`

**Comment by mxmlnglt** [comment] 2023-05-10 14:27
Still relevant today (I can't test as of right now...)

**Comment by Rawi01** [comment] 2023-05-13 14:20
Still relevant and a duplicate of #2869

**Closed by Rawi01** 2023-05-13 14:20 UTC
