### ISSUE TITLE
[BUG] Error when compiling with Java 19

### ISSUE THREAD

**Issue by oo00spy00oo** [projectlombok/lombok#3296] opened 2022-11-15 03:34 UTC
**Describe the bug**

Error when compile with Java 19

```
error: Error during the transformation of '<Class Name>'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 63
```

**Version info (please complete the following information):**
 - Lombok version: 1.18.24
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse: Java 19

**Comment by popovanastas** [comment] 2022-11-16 12:18
Duplicate of #3264

**Closed** 2022-11-16 17:39 UTC
