### ISSUE TITLE
[BUG] Lombok annotation handler class lombok.eclipse.handlers.<class>$<constructor> failed 

### ISSUE THREAD

**Issue by nvs-github** [projectlombok/lombok#3628] opened 2024-03-15 20:44 UTC
**Describe the bug**
After installing lombok on STS, the error described in the title appears in the Problems section

It is important to clarify that it has been validated that Lombok is installed correctly, in the Help window --> About Spring Tool Suite 4, the message appears:

Lombok v1.18.30 "Envious Ferret" is installed. https://projectlombok.org/

The errors it marks are the following:
Lombok annotation handler class lombok.eclipse.handlers.HandleToString failed - See error log.
Lombok annotation handler class lombok.eclipse.handlers.HandleConstructor$HandleNoArgsConstructor failed - See error log.

**To Reproduce**
Fresh install of STS, installation of Lombok, clean and compile the Demo project

[demo.zip](https://github.com/projectlombok/lombok/files/14620556/demo.zip)

**Expected behavior**
To compile correctly without errors

**Version info (please complete the following information):**
OS
Ubuntu 22.04.4 LTS

Spring Tool Suite 4 
Version: 4.22.0.RELEASE
Build Id: 202403071427
Revision: 44291b464093d161f115d8e16059e5272ed3c81d

Lombok v1.18.30 "Envious Ferret" is installed. https://projectlombok.org/

Java Version:
/home/user/sts-4.22.0.RELEASE/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_17.0.10.v20240120-1143/jre/bin/java
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode)

**Additional context**
I add the Demo project created to reproduce the problem, I have just installed STS and Lombok, so I don't have any other plugins or aditional software but the first time I get this error was on my work's laptop with Windows 10 Enterprise 64 bits and Java JDK 20.0.1-x86, so the problem is the same in both Operative Systems and with or without plugins

**Comment by jdimeo** [comment] 2024-03-15 23:21
I believe this is a duplicate of https://github.com/projectlombok/lombok/issues/3620

**Comment by Rawi01** [comment] 2024-03-16 09:17
It is

**Closed by Rawi01** 2024-03-16 09:17 UTC
