### ISSUE TITLE
[BUG] log4j出现严重漏洞，请升级log4j至2.15版本

### ISSUE THREAD

**Issue by 371486927** [projectlombok/lombok#3062] opened 2021-12-10 07:21 UTC
https://open.work.weixin.qq.com/wwopen/mpnews?mixuin=3_HVCQAABwBHKvwGAAAUAA&mfid=WW0310-6x9-BwAABwB7tPj8XTxKnQJm-1T5c&idx=0&sn=d38bbc1075de2cdc8c9f67fc6d09894a&notreplace=true

log4j出现严重漏洞，请升级log4j至2.15版本

**Comment by rspilker** [comment] 2021-12-11 23:01
I just assume this is a duplicate of #3063 3063

**Closed by rspilker** 2021-12-11 23:01 UTC
