### ISSUE TITLE
[FEATURE] @Record

### ISSUE THREAD

**Issue by almson** [projectlombok/lombok#3201] opened 2022-05-24 11:53 UTC
Java 17 records are half-baked (see below). And they're only 17+. Lombok's Data is a similar, better solution, but it differs enough in its behavior from records as to be unnecessarily confusing and incomplete.

The problems I've found with Java 17 records:

  - *Main problem:* Javadoc is weird and/or broken and/or not standardized and/or asinine (totally ruins records!)
  - bad syntax, especially for multi-line declarations. Eg, comma on last component is illegal
  - toString ignores arrays

Problems with `@Data`:

  - Adding a constructor deletes the autogenerated "canonical" one (need to use Tolerate)
  - fields aren't private+final by default
  - non-static nested classes are permitted
  - non-final fields are permitted (not sure if it's good or bad)
  - accessors aren't fluent (ok, I know you want this configured at project level, but it would help to just match Records)

**Comment by Vyacheslav-Lapin** [comment] 2022-05-24 12:14
Maybe, @Value is more similar analog for Java 14+ records, then @Data for comparing?..

**Comment by rzwitserloot** [comment] 2022-05-27 15:16
> Java 17 records are half-baked (see below).

As co-author of lombok's `@Data` and `@Value` there's not much point in chiming in here with an Amen! Preach it! - I might be a _tad_ biased. But, let's just say, no argument from me on this :)

NB: Just as I was regretting the choice to even introduce 'fluent' (that is, just `.name()`, not `.getName()`), given that the java community has clearly standardized on `getX()`, and whilst wordy, it actually helps in IDEs: If you want a property, the shortcut key is effectively `.geCTRL+SPACE` which shows you specifically all getters and nothing else, which is nice. Aaaaaannnnnnnd the openjdk team throws out the backwards incompatible bombshell of going 'fluent' for their `record`s, making the best API in the entire JDK (`java.time`) look outdated now. Oof.

> Main problem: Javadoc is weird and/or broken and/or not standardized and/or asinine (totally ruins records!)

Huh. Didn't know that. But that does sound like something that might be fixed in the future; I rather doubt the current status of the notion of backwards compatibility amongst the OpenJDK team (which is really low - they break stuff all the time now) would mean they'd hesitate to clean up javadoc. Nobody ever promised javadoc gen to be super stable.

> bad syntax, especially for multi-line declarations. Eg, comma on last component is illegal

This matches the notion that method invocation argument lists can't have trailing commas either. But, speaking of which, __that could change__, I know quite a bit (lombok, ya know) about the parser architecture and syntactic definition of java / `javac`, and this could be added without much hassle. I've planned to advocate for this when the time is right. Still, sure, yes. It's annoying right now, and somewhat of a weird oversight this wasn't added. I'm not quite sure how `@Data` and co fix this, though.

> Problems with `@Data`:

Data fundamentally has nothing to do with records at all. You're comparing guns and grandmas.

`@Value` - that's lombok's equivalent. So let's evaluate your list of 5 issues in light of `@Value` and not `@Data`, which is explicitly designed for mutable objects (whereas record enforcing immutability). `@Value` is designed for immutables (it does not quite enforce, you can use `@NonFinal`, for example). I'll also shuffle your bullets around to be in the most convenient order for explanations.

> fields aren't private+final by default

* They are, with `@Value`. The class itself is also made `final` (similar to how `record` is final).
* Unlike records, if you know what you're doing and really want to opt out of this, you _can_, with `@NonFinal`, and you can of course just explicitly shove a `protected` or what not (or even `@PackagePrivate`). We want to steer programmers in the right direction, and we don't want to build features which do not appear to be useful except for highly dubious code. However, that leaves plenty of room for flexibility: We allow you to make non-final fields, non-final classes, and non-private fields _if_ you explicitly opt for these things. By design.

> non-static nested classes are permitted

I do not understand why records don't permit them. What confused hoops has the OpenJDK team jumped through? Perhaps the simplest one: Hey, we can always choose to make that legal later on in a point release; we cannot choose to make it __illegal__, that'd be backwards incompatible, so lets err on the side of caution. However, it is just _weird_, especially if you consider `record` just a convenient shortcut to make an immutable class and get a boatload of boilerplate pre-generated for you (including the ability to deconstruct in java18's new pattern features, though I think the idea is that non-records can specify deconstruction recipes in a later java release, so still pre-fill boilerplate, really). You really need to consider `record` as quite fundamentally a very different concept in order to justify the choice.

Point is, lombok clearly chose the interpretation that a `@Value` class is just a class, with a whole bunch of convenience generated for you. So why in the blazes would we deny this?

There's nothing fundamentally incompatible with allowing non-static inner classes here. In contrast to e.g. defaulting them the class itself to be non-`final` - a non-`final` class that SEEMS immutable (all fields are `final`, and, why not, are all of immutable types themselves) doesn't really act like it if anyone can just subclass and add mutable state. You can't make that kind of argument for the presence of non-static inners: How does the existence of non-static inners make the record (or `@Value class`) any less immutable or value-like or record-like?

> non-final fields are permitted (not sure if it's good or bad)

As explained earlier, by design. You have to explicitly opt in - if you just write `String foo;` it'll be made `final`, you'd have to write `@NonFinal String foo;`.

> accessors aren't fluent

Yes, by design. OpenJDK messed this up. See `LocalDate` and friends, and ~75% of the java ecosystem, which has non-fluent getters. When in rome, act like romans. Which is why its weird that the Roman Senate chose to act like a bunch of barbarians from Gaul on this choice!

> Adding a constructor deletes the autogenerated "canonical" one (need to use Tolerate)

The trickiest one here. But, this is really the only bullet that is left standing to some extent, and it's a dubious one at that. It's not worth introducing `@Record` _just_ to effectively mean `@Value @AllArgsConstructor`, surely you'd agree.

Thus, denied - because the good news is, this basically exists already, it's just called `@Value`, not `@Record`.

NB: Once the JDK grows the ability for classes to specify deconstruction recipes we will be adding that to `@Value`, probably out of the box. I doubt it'll be backwards incompatible outside of ridiculously contrived cases. Let's hope so!

> Adding a constructor deletes the autogenerated "canonical" one (need to use Tolerate)

**Closed by rzwitserloot** 2022-05-27 15:16 UTC

**Comment by almson** [comment] 2022-06-01 07:09
Sorry, didn't see @Value. But hopefully the javadoc comment was useful to you. (It shows how bad the current crop of JDK devs are that they don't even think about documentation.)

Off-topic, but my view is that getters/setters make sense for mutable state, but final fields should just be public. In any case, the JDK has plenty of fluent properties. These have been trendy since NIO in Java 1.4.

Nonstatic-by-default local classes are annoying. They're unnecessary 99% of the time. The extra reference just makes work for the GC and JIT. Makes sense that a simple bag of data would be static.

Anyway, it's always pleasant to talk to you)
