### ISSUE TITLE
Unexpected behaviour with newly added @Builder.Default

### ISSUE THREAD

**Issue by 5im5im** [projectlombok/lombok#1444] opened 2017-07-18 15:55 UTC
Hey there

I have problems with the newly added @Builder.Default in v1.16.18.
It changes the behaviour of manual created constructors. It will leed to ignore default values of attributes (like `private String b = "b";`) if annotated with `@Builder.Default` . I reduced this issue to the following two classes and test case which shows my expectations.

classes:
```
public class Lombok {
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class WithBuilderDefaultAnnotation {
        private String a;

        @Builder.Default
        private String b = "b";

        public WithBuilderDefaultAnnotation(String a) {
            this.a = a;
        }
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class WithoutBuilderDefaultAnnotation {
        private String a;

        private String b = "b";

        public WithoutBuilderDefaultAnnotation(String a) {
            this.a = a;
        }
    }
}
```

unit tests:
```
public class LombokTest {

    /** SUCCESSFUL, entity.getB() returns "b" */
    @Test
    public void testA() {
        Lombok.WithoutBuilderDefaultAnnotation entity = new Lombok.WithoutBuilderDefaultAnnotation("hello world");
        assertEquals("b", entity.getB());
    }

    /** FAILS, entity.getB() returns null */
    @Test
    public void testB() {
        Lombok.WithBuilderDefaultAnnotation entity = new Lombok.WithBuilderDefaultAnnotation("hello world");
        assertEquals("b", entity.getB());
    }

    /** SUCCESSFUL, entity.getB() returns null as expected because Lombok.Working has NO {@link lombok.Builder.Default} annotation (maybe this would be the default behaviour later in Lombok?) */
    @Test
    public void testC() {
        Lombok.WithoutBuilderDefaultAnnotation entity = Lombok.WithoutBuilderDefaultAnnotation.builder().a("hello world").build();
        assertNull(entity.getB());
    }

    /** SUCCESSFUL, entity.getB() returns "b" as expected because Lombok.NotWorking has a {@link lombok.Builder.Default} annotation */
    @Test
    public void testD() {
        Lombok.WithBuilderDefaultAnnotation entity = Lombok.WithBuilderDefaultAnnotation.builder().a("hello world").build();
        assertEquals("b", entity.getB());
    }
}
```

**Comment by kevcodez** [comment] 2017-07-20 11:37
See https://github.com/rzwitserloot/lombok/issues/1347 and https://github.com/rzwitserloot/lombok/pull/1429

**Comment by Rawi01** [comment] 2024-03-12 23:11
Duplicate of #2340

**Closed by Rawi01** 2024-03-12 23:11 UTC
