### ISSUE TITLE
[BUG] @Data won't generate getter and setters when two field have similar names

### ISSUE THREAD

**Issue by BasZhang** [projectlombok/lombok#3342] opened 2023-02-03 10:08 UTC
Demo code is here:
`import lombok.Data;

@ Data
public class CC {

    private DT data;

    @Data
    public static class DT {

        private Info info;

        @Data
        public static class Info {

            private String bitrate;
            private String bitRate;
        }
    }

    public static void main(String[] args) {
        var sut = new CC();
        sut.getData().getInfo().setBitrate(sut.getData().getInfo().getBitRate());
    }
}
`

It has no warning when I type it in IDE, but It won't compile with Maven or Gradle. Maybe because the two fields have similar names.
I tried Lombok version 1.18.24 and 1.18.26.

**Comment by dstango** [comment] 2023-02-03 12:58
Duplicate of #2130

**Closed** 2023-05-10 15:06 UTC
