### ISSUE TITLE
[FEATURE] Allow mapping on @SneakyThrows

### ISSUE THREAD

**Issue by trajano** [projectlombok/lombok#3108] opened 2022-02-04 17:44 UTC
**Describe the feature**

Lombok

```
@SneakyThrows(exceptionClass=SQLException.class, runtimeExceptionClass=PersistenceException.class)
@SneakyThrows(exceptionClass=IOException.class, runtimeExceptionClass=UncheckedException.class)
foo() {
    ... something that throws SQLException }
}
```

delombok

```
foo() {
  try {
    ... something that throws SQLException and IOException
  } catch (SQLException e) {
    throw new PersistenceException(e);
  } catch (IOException e) {
    throw new UncheckedIOException(e);
  }
}
```

**Describe the target audience**

Those that deal with low level JDBC that don't want to deal with SQLException, BUT want to know that it is a persistence error rather than unwrapping.  Same with those using IO.

**Additional context**
I should be allowed to handle multiple BUT for older JDKs that don't support repeated ones it can be
```
@SneakyThrows(mappings={
  @SneakilyThrow(exceptionClass=SQLException.class, runtimeExceptionClass=PersistenceException.class)
  @SneakilyThrow(exceptionClass=IOException.class, runtimeExceptionClass=UncheckedException.class)
})
```

That being the case we can add `@SneakilyThrow` as a new annotation instead.

**Comment by rzwitserloot** [comment] 2022-02-04 18:11
Duplicate of #1289.

**Closed by rzwitserloot** 2022-02-04 18:11 UTC
