### ISSUE TITLE
Can you make APIs lombok a librarie? [FEATURE] 

### ISSUE THREAD

**Issue by RobertoMike** [projectlombok/lombok#3580] opened 2024-01-08 13:50 UTC
**Describe the feature**
You could create a library with your own internal APIs which you can use to create custom annotations for your own projects and libraries, because these annotations cannot be implemented within the Lombok project, but would be very useful for these libraries and projects. This would open up a world of possibilities, even for those smaller libraries.

**Describe the target audience**
This could be useful for many people, projects and libraries, thus making their work easier.

**Additional context**
I make this request for personal open projects that I am carrying out, but I consider that it would not only be useful for me, but also for many other people.

**Comment by rzwitserloot** [comment] 2024-01-13 02:02
Duplicate of #3581 presumably. Also, this bug report/feature request is vague, so, even if it isn't, closed due to low quality.

**Closed by rzwitserloot** 2024-01-13 02:02 UTC
