### ISSUE TITLE
[BUG] Eclipse freezes code completing large enum (out of memory) caused by lombok ShadowClassLoader->EclipseAST

### ISSUE THREAD

**Issue by Kademlia** [projectlombok/lombok#3540] opened 2023-11-07 18:44 UTC
**Describe the bug**
Lombok seems to get stuck in TransformEclipseAST, EclipseAST, transformationStates generating near endless/looping results.
This will in the end fill all memory available and make eclipse unresponsive.

This seems to be caused by the ShadowClassLoader getting stuck when generating EclipseAST and doing that over and over again, generating several GB of WeakHashMap entries per typed character for the code completion of a large enum.

Each spawned Worker per started code-completion will get stuck in EclipseAST.drill(...)
![image](https://github.com/projectlombok/lombok/assets/152798/d4360331-7a4a-4964-bbca-55b0fa804a4b)

**To Reproduce**
This one is **very** strange. So I spend some time to generate a minimal project to reproduce the bug. The project contains a Rip.java file. Inside there is a single code-line commented out. By reactivating the line and starting to type '.coal' or any other existing enum the problem should appear. Should make vanilla eclipse 2023-09 unresponsive. By typing very slowly (1 char ever 5 seconds) the editor does not freeze with 8GB memory allocated to eclipse.

Example Project: https://github.com/Kademlia/buggit

**Expected behavior**
The memory footprint of eclipse should not explode on every typed character (code-completion trigger).

**Version info:**
 - Lombok version 1.18.30
 - Platform Eclipse Version: 2023-12 M2 (4.30.0 M2), Build id: 20231026-1433
 - as well as **Vanilla** Platform Eclipse Version: 2023-09 (4.29.0) Build id: 20230907-1323
 - Windows 10 64Bit, 22H2

**Additional context / Analysis**
I did some digging, here the most relevant parts:

**Fixing the project (still slowed a lot by lombok but not crashing)**:
1. Removing 	<maven.compiler.source>...</maven.compiler.target> from the pom.xml will FIX the bug
2. Removing the **empty folder** from src\test\java\org\bukkit will fix the bug as well
3. Removing the module-info.java will fix the bug as well
4. Removing the **switch-statement** from Material.java will fix the bug

Additional debugging info:
Minified Video of me encountering the bug: https://www.youtube.com/watch?v=KEbYkwuzMsQ

![image](https://github.com/projectlombok/lombok/assets/152798/24284736-fe05-48a4-a3da-efd2edab4cf4)
![image](https://github.com/projectlombok/lombok/assets/152798/8571868f-8aa5-4550-a137-93204fb18fa8)
![image](https://github.com/projectlombok/lombok/assets/152798/a1797694-bd90-40ff-bd72-4bb5bfa19b81)
![image](https://github.com/projectlombok/lombok/assets/152798/1f425b01-7179-4474-ac30-cf243690779e)
![image](https://github.com/projectlombok/lombok/assets/152798/111c9f68-81c5-4c37-820b-919739025085)
![image](https://github.com/projectlombok/lombok/assets/152798/9bb48b1e-c16e-4f15-be0e-8d97a00ab743)

**Comment by Rawi01** [comment] 2023-11-10 16:28
Great bug report :+1:

I managed to reproduce it by adding the empty test folder to the sample project. This is definitely one of the strangest bugs I have seen in a long time.

**Comment by Kademlia** [comment] 2023-11-10 21:47
Oh sorry about the empty folder, even had that on the list but still managed to miss it in the end on commit.

Some more tests I tried:

- Removing lombok from the pom & module-info does not change anything.
- Running **dangerousconfig.lombok.disable=true** fixes it

I tried to make a minimal change to lombok as follows (or at least add some log-lines to get an idea of whats going on):
- Add new config setting to force lombok to _only consider recalculation when a file is saved_ (or at least _not when code completion is running_)
- As in my project code-completion is laggy because of lombok even if this specific report would be fixed.

Unfortunately I am not familiar enough with the code and got stuck setting it up. Maybe you spot something obvious?
1. Checked out 1.18.30 https://github.com/projectlombok/lombok/commit/b118bea124bc5aef59cb0c5cac4a086e1e3d98f2
2. Setup Apache Ant(TM) version 1.10.14 compiled on August 16 2023
3. Ran ant eclipse, used Lombok-test Javac 14 with 830 tests successful and ant dist: Seems to work
4. But adding a single log line makes it break in most files and all code-completion for some reason

```
	public static boolean alreadyTransformed(CompilationUnitDeclaration ast) {
		State state = transformationStates.get(ast);
		warning("alreadyT? " + state + " " + ast, new NullPointerException("ye"));
		if (state == State.FULL) return true;
		[...]
```

6. test.eclipse-202212 runs fine
7. Running test.eclipse-2022-03-full fails for me on JBR-21+9-212.1-nomod (most recent JDK JBR 21 Version)
```

[junit] [FAIL] withGetterDifferentFile(lombok.eclipse.refactoring.RenameTest)
    [junit] expected:<...               return new A().get[New]String();
    [junit]     }
    [junit] }> but was:<...             return new A().get[]String();
    [junit]     }
    [junit] }>
    [junit] [FAIL] withGetter(lombok.eclipse.refactoring.RenameTest)
    [junit] expected:<...est() {
    [junit]             return get[New]String();
    [junit]     }
    [junit] }> but was:<...est() {
    [junit]             return get[]String();
    [junit]     }
    [junit] }>
```

**Comment by Rawi01** [comment] 2023-11-10 22:19
Happens :)

I think the root cause is an eclipse problem, it parses the module-info and the enum for every constant and doesn't cache the result. Lombok runs after every parse, performs its own transformations and stores the state for the compilation unit. The used `WeakHashMap` for the state fills up to fast for the garbage collector. 

Changing the maven dependency doesn't change how lombok works in eclipse, you have to update the javaagent in your `eclipse.ini`.

I don't know why your tests fail if you add a single line, we also use Github Actions to run the test and there are no problems.

I pushed a fix for it, can you try if it also works for you?  ([lombok.jar](https://github.com/Rawi01/lombok/suites/18097217191/artifacts/1043007184))

**Comment by Kademlia** [comment] 2023-11-10 23:28
Can confirm fixed, thank you

**Comment by Rawi01** [comment] 2023-11-11 15:27
Thanks for testing. I'd like to report the problem to Eclipse if that's okay for you.

**Comment by Kademlia** [comment] 2023-11-11 18:56
Yes I reported a possibly related one with similar consequences here, got fixed in 2023-12-M1 https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1100

**Closed** 2023-11-13 11:51 UTC
Labels: bug, eclipse, accepted
