### ISSUE TITLE
[FEATURE] @SuperBuilder support build with superclass

### ISSUE THREAD

**Issue by cwt9562** [projectlombok/lombok#3132] opened 2022-03-09 07:05 UTC
i have two class like:
```
@SuperBuilder
class Parent {
    String x;
}

@SuperBuilder
class Child {
    String y;
}
```
then, i want to new a Child object from a Parent object, just like this:
```
Parent parent = Parent.builder()
    .x("1")    
    .build();
Child child = Child.builder()
    .withParent(parent)
    .y("2")
    .build();
```
how could i do this?

**Comment by janrieke** [comment] 2022-03-09 09:31
Duplicate of #2374 

Here's a (hacky) solution for your problem: https://stackoverflow.com/a/66817135/10026074

**Closed** 2022-03-09 13:57 UTC

**Comment by cwt9562** [comment] 2022-03-10 02:13
> Duplicate of #2374
> 
> Here's a (hacky) solution for your problem: https://stackoverflow.com/a/66817135/10026074

ok，it works.
and then, i make some modifications 

```
@SuperBuilder(toBuilder = true)
public class GrandParent {
    private Integer x;

    public abstract static class GrandParentBuilder<C extends GrandParent, B extends GrandParent.GrandParentBuilder<C, B>> {
        protected B $fillValuesFromGrandParent(GrandParent instance) {
            $fillValuesFromInstanceIntoBuilder(instance, this);
            return self();
        }
    }
}

@SuperBuilder(toBuilder = true)
public class Parent extends GrandParent {

    private Integer y;

    public static Parent.ParentBuilder<?, ?> toBuilder(GrandParent instance) {
        return new Parent.ParentBuilderImpl().$fillValuesFromGrandParent(instance);
    }

    public abstract static class ParentBuilder<C extends Parent, B extends Parent.ParentBuilder<C, B>> extends GrandParent.GrandParentBuilder<C, B> {
        protected B $fillValuesFromParent(Parent instance) {
            $fillValuesFromInstanceIntoBuilder(instance, this);
            return self();
        }
    }
}

@SuperBuilder(toBuilder = true)
public class Child extends Parent {
    public Integer z;

    public static ChildBuilder<?, ?> toBuilder(GrandParent instance) {
        return new ChildBuilderImpl().$fillValuesFromGrandParent(instance);
    }

    public static ChildBuilder<?, ?> toBuilder(Parent instance) {
        return new ChildBuilderImpl().$fillValuesFromParent(instance);
    }
}
```
```
GrandParent grandParent = GrandParent.builder().x(1).build();
Parent parent = Parent.toBuilder(grandParent).y(2).build();
Child child1 = Child.toBuilder(grandParent).z(3).build();
Child child2 = Child.toBuilder(parent).z(4).build();
```

**Comment by cwt9562** [comment] 2022-03-10 07:12
i found the GrandParend's field x was missing when using Child.toBuilder(parent)
so, update
```
@SuperBuilder(toBuilder = true)
public class GrandParent {
    private Integer x;

    public abstract static class GrandParentBuilder<C extends GrandParent, B extends GrandParent.GrandParentBuilder<C, B>> {
        protected B $fillValuesFromGrandParent(GrandParent instance) {
            $fillValuesFromInstanceIntoBuilder(instance, this);
            return self();
        }
    }
}

@SuperBuilder(toBuilder = true)
public class Parent extends GrandParent {

    private Integer y;

    public static Parent.ParentBuilder<?, ?> toBuilder(GrandParent instance) {
        return new Parent.ParentBuilderImpl().$fillValuesFromGrandParent(instance);
    }

    public abstract static class ParentBuilder<C extends Parent, B extends Parent.ParentBuilder<C, B>> extends GrandParent.GrandParentBuilder<C, B> {
        protected B $fillValuesFromParent(Parent instance) {
            $fillValuesFromParent((GrandParent) instance);
            $fillValuesFromInstanceIntoBuilder(instance, this);
            return self();
        }
    }
}

@SuperBuilder(toBuilder = true)
public class Child extends Parent {
    public Integer z;

    public static ChildBuilder<?, ?> toBuilder(GrandParent instance) {
        return new ChildBuilderImpl().$fillValuesFromGrandParent(instance);
    }

    public static ChildBuilder<?, ?> toBuilder(Parent instance) {
        return new ChildBuilderImpl().$fillValuesFromParent(instance);
    }
}


GrandParent grandParent = GrandParent.builder().x(1).build();
Parent parent = Parent.toBuilder(grandParent).y(2).build();
Child child1 = Child.toBuilder(grandParent).z(3).build();
Child child2 = Child.toBuilder(parent).z(4).build();
```

**Comment by skyblackhawk** [comment] 2025-02-25 16:09
I can't find Parent.ParentBuilderImpl() in lombok 1.18.34 !!!
