### ISSUE TITLE
[BUG] Eclipse 4.23 refactor/rename from within Java Source Editor throws java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by andi-huber** [projectlombok/lombok#3134] opened 2022-03-12 06:12 UTC
Given a fresh _Eclipse_ install from upcoming 4.23.0 Release (Candidate Build: 4.23RC2a), it appears that when Lombok is installed as java agent in eclipse.ini
```
...
-vmargs
-javaagent:xxx\eclipse\lombok-1.18.22.jar
...
```
the _Eclipse_ refactor feature no longer works from within the _Source Editor_ window.

**To Reproduce**
Given plain Java (no Lombok) ...
```
public static void main(String[] args) {
   var message = "Hallo World";
   System.out.println(message);
}
```
when trying to refactor/rename the `message` variable (e.g. select the text and use the context menu), _Eclipse_ throws a `java.lang.VerifyError.`

**Version info:**
 - Lombok version 1.18.22, but also a [latest build](https://github.com/projectlombok/lombok/commit/8c3ff7e9b08c4bf9c2b23cffb6042c31258e3ebb) from the 'master' branch has same issue
 - Platform Windows with Java 17.0.2 as shipped with the _Eclipse_ Release Candidate (Candidate Build: 4.23RC2a)

**Additional context**
Eclipse also has a _Code Outline_ view, from where one can initiate a refactor/rename e.g. on class fields. It appears that with that there are no issues.

**Comment by andi-huber** [comment] 2022-03-12 06:13
```
eclipse.buildId=4.23.0.I20220223-1800
java.version=17.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file D:\development\workspaces\oxygen\.metadata\.bak_0.log
Created Time: 2022-03-12 06:45:50.206

org.eclipse.ui
Error
Sat Mar 12 06:45:50 CET 2022
Unhandled event loop exception

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/eclipse/jdt/internal/corext/dom/LinkedNodeFinder.findByNode(Lorg/eclipse/jdt/core/dom/ASTNode;Lorg/eclipse/jdt/core/dom/Name;)[Lorg/eclipse/jdt/core/dom/Name; @11: invokestatic
  Reason:
    Type '[Lorg/eclipse/jdt/core/dom/Name;' (current frame, stack[0]) is not assignable to '[Lorg/eclipse/jdt/core/dom/SimpleName;'
  Current Frame:
    bci: @11
    flags: { }
    locals: { 'org/eclipse/jdt/core/dom/ASTNode', 'org/eclipse/jdt/core/dom/Name', '[Lorg/eclipse/jdt/core/dom/Name;' }
    stack: { '[Lorg/eclipse/jdt/core/dom/Name;' }
  Bytecode:
    0000000: 2a2b b801 044d 2cc6 0008 2cb8 016b b02b
    0000010: b601 06b6 00f6 3e1d 101e 9f00 0f1d 100a
    0000020: 9f00 091d 1012 a000 32bb 00d0 59b7 00d2
    0000030: 3a04 bb01 0959 2b19 04b7 010b 3a05 2a19
    0000040: 05b6 00d8 1904 1904 b600 dcbd 0107 b600
    0000050: dfc0 010e b801 6bb0 04bd 0107 5903 2b53
    0000060: b801 6bb0                              
  Stackmap Table:
    append_frame(@15,Object[#270])
    append_frame(@41,Integer)
    same_frame(@88)

	at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.start(RenameLinkedMode.java:238)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RenameJavaElementAction.run(RenameJavaElementAction.java:250)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RenameJavaElementAction.doRun(RenameJavaElementAction.java:190)
	at org.eclipse.jdt.internal.ui.refactoring.actions.RenameJavaElementAction.run(RenameJavaElementAction.java:162)
	at org.eclipse.jdt.ui.actions.RenameAction.run(RenameAction.java:121)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:278)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:252)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:121)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1280)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1062)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1087)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1072)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:4260)
	at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:4110)
	at org.eclipse.swt.widgets.Composite.translateMnemonic(Composite.java:1251)
	at org.eclipse.swt.widgets.Composite.translateMnemonic(Composite.java:1254)
	at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:4128)
	at org.eclipse.swt.widgets.Display.translateMnemonic(Display.java:4916)
	at org.eclipse.swt.widgets.Display.filterMessage(Display.java:1298)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3628)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

**Comment by rzwitserloot** [comment] 2022-03-13 12:36
Relevant source files:

* [SimpleName](https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/SimpleName.java) (a subclass of Name).
* Line 238 in [RenameLinkedMode](https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.ui/ui%20refactoring/org/eclipse/jdt/internal/ui/refactoring/reorg/RenameLinkedMode.java) indeed appears to invoke [LinkedNodeFinder.findByNode](https://git.eclipse.org/c/jdt/eclipse.jdt.ui.git/tree/org.eclipse.jdt.core.manipulation/core%20extension/org/eclipse/jdt/internal/corext/dom/LinkedNodeFinder.java).
* Just looking at it, I don't get this error - there are 2 overloads for findByNode; one based on SimpleName which returns SimpleName[], and one based on Name which returns Name[] - the Name based version is involved as per the signature in that error, but it whinges that a Name[] is not assignable to SimpleName[]. Sure, but.. which code is attempting to do that, then? These are the 'latest' versions I linked to. I'd have expected this if the findByNode overloads had been unified into a single method or some such.

**Comment by rzwitserloot** [comment] 2022-03-13 12:40
In that code, the result is in fact assigned to an `ASTNode[]`,but that's a local var so type info is presumably not verified there. More generally in JVMese you can just assign a `Child[]` ref to a place where `Parent[]` is expected and this works even though variance wise it shouldn't - that's just how java is defined. If it was our code that means we can just return a `SimpleName[]` where previously we returned a `Name[]`, but it doesn't appear to (directly) be our code - or am I missing something and is this a method we are agent-modifying?

**Comment by rzwitserloot** [comment] 2022-03-13 12:42
D'oh, @Rawi01 already figured it out.

**Closed** 2022-03-13 12:44 UTC
Labels: bug, eclipse, accepted

**Comment by Rawi01** [comment] 2022-03-13 12:54
I self-assigned it to let you know that I'm working on it :smile: 

The `Name[]` method is the new one and it fails because it tries to call the `SimpleName[]` patch. Our old patch code changed both methods so I had to modify it and add a new patch for the new method.

**Comment by andi-huber** [comment] 2022-03-13 15:07
Impressive response time. Fix works for me. Thank you so much!

**Comment by aasjpvm** [comment] 2022-03-16 20:19
hope all can be solved soon, I find this same issue today when updated accidentally eclipse

**Comment by Rawi01** [comment] 2022-03-16 21:40
JDK 18 (release in 6 days) also requires some changes so I guess there might be a new release version soon. I uploaded a [pre-built version](https://github.com/projectlombok/lombok/files/8274291/lombok.zip) if you need the fix right now.

**Comment by jakobklein** [comment] 2022-03-17 10:22
Thx for the quick fix. The pre-built works for me.

**Comment by dstango** [comment] 2022-03-21 22:27
Can we get an updated snapshot version? As people update to Eclipse 2022-03 they come over to the eclipse side with puzzled bug reports, and there are surely more that don't report it but blame it on Eclipse ...
Would be great to have be easily able to help them out at least with the snapshot version.

**Comment by rzwitserloot** [comment] 2022-03-22 02:10
The current snapshot version _is_ updated, no?

**Comment by andi-huber** [comment] 2022-03-22 04:59
I updated the issue description, in case people land on this issue page, coming from any context, so they quickly get directed to the fixed snapshot download.

**Comment by dstango** [comment] 2022-03-22 06:03
> The current snapshot version _is_ updated, no?

This guy says it isn't: https://bugs.eclipse.org/bugs/show_bug.cgi?id=579339

**Comment by andi-huber** [comment] 2022-03-22 06:14
I updated the link to the fixed version in the description (https://github.com/projectlombok/lombok/files/8274291/lombok.zip).
(just in case the edge version is not up to speed - did not check)

**Comment by dstango** [comment] 2022-03-22 07:34
thanks!

**Comment by dstango** [comment] 2022-03-22 07:42
Question: might this issue be related, too? https://bugs.eclipse.org/bugs/show_bug.cgi?id=579341

**Comment by davidsedlar** [comment] 2022-03-23 09:31
I was so perturbed why my new Eclipse won't rename anything anymore! THhanks for the quick fix, Lombok is the best!

**Comment by shankarwww** [comment] 2022-03-28 21:28
It seems the issue is still not completely fixed. Try to rename the file using Crtl+Shift+R by clicking the on the file in the package explorer. The window and different options in the toolbar menu starts flickering.

**Comment by Rawi01** [comment] 2022-03-28 21:43
@shankarwww If I press Ctrl+Shift+R it opens a seperate rename dialog and I cannot see any flickering. Can you share some more details?

**Comment by shankarwww** [comment] 2022-03-28 23:11
![sts_flickering_issue](https://user-images.githubusercontent.com/18091406/160502083-a1576f9d-9bc0-4821-b57b-b3193057fd4d.png)

please find the details in above pic

**Comment by dstango** [comment] 2022-03-29 05:17
I had a "flickering issue" with something totally unrelated to lombok, but what was the same was that the keyboard shortcut was ambiguous - I had two commands associated to the same key binding.
Looks like that's the case here.
Suggestions:
* remove keybinding of rename and see if issue persists.
* if this helps, please file a bug on the eclipse side because of the flickering.

**Comment by dstango** [comment] 2022-03-29 17:00
@shankarwww Hopefully this will help resolve it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=579483

**Comment by user20161119** [comment] 2022-04-22 06:21
after i tested with [1.18.24](https://projectlombok.org/downloads/lombok.jar) and sts Version: 4.14.0.RELEASE
Build Id: 202203131612

the rename not working again,and then i uninstall lombok,rename work again

**Comment by user20161119** [comment] 2022-04-26 02:06
> @user20161119 In eclipse menu: `Window`, `Show View`, `Error Log`. Fetch the relevant log and paste the exception trace and all details. Because we fixed this, and I don't have an STS installation handy.

I rolled back to following version ,and it's work
![image](https://user-images.githubusercontent.com/123967/165204984-a1bb48b0-f206-4e52-87b0-880cf79146d1.png)

**Comment by rzwitserloot** [comment] 2022-04-27 23:38
@user20161119 That is not the error log. The error log contains, well, errors, and generally includes a stack trace. There's nothing we can do (short of just downloading STS, clicking around, and praying we hit the same issue. We're not going to do that) without this information, and the issue will remain closed until it is provided.
