### ISSUE TITLE
[BUG] 1.18.34 regression: /* */ comments above javadoc causes "HandleConstructor$HandleAllArgsConstructor failed"

### ISSUE THREAD

**Issue by atnak** [projectlombok/lombok#3733] opened 2024-08-28 07:24 UTC
**Describe the bug**
Having `/* */` comments above javadoc when using `@AllArgsConstructor` causes `Lombok annotation handler class lombok.eclipse.handlers.HandleConstructor$HandleAllArgsConstructor failed`.

**To Reproduce**
Here's minimal Java code to reproduce:

```java
import lombok.AllArgsConstructor;

@AllArgsConstructor
public class Foo {

	/* foo */

	/**
	 * i
	 */
	int i;
}
```

**Expected behavior**
Ignore the `/* */` comments and not fail.

**Version info (please complete the following information):**
 - Lombok version: 1.18.34
 - Platform:
    ```
    eclipse.buildId=4.32.0.20240606-1231
    java.version=22.0.2
    java.vendor=Eclipse Adoptium
    BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_AU
    ```

**Additional context**
Stack trace follows:
```
java.lang.StringIndexOutOfBoundsException: Range [12, 3) out of bounds for length 45
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
	at java.base/java.lang.String.substring(String.java:2876)
	at lombok.eclipse.handlers.EclipseHandlerUtil.getDocComment(EclipseHandlerUtil.java:2823)
	at lombok.eclipse.handlers.HandleConstructor.generateConstructorJavadoc(HandleConstructor.java:597)
	at lombok.eclipse.handlers.HandleConstructor.generate(HandleConstructor.java:290)
	at lombok.eclipse.handlers.HandleConstructor.generateConstructor(HandleConstructor.java:246)
	at lombok.eclipse.handlers.HandleConstructor$HandleAllArgsConstructor.handle(HandleConstructor.java:165)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:269)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:226)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:187)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:104)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:146)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:272)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11535)
...
```

**Comment by atnak** [comment] 2024-08-28 07:34
bkballoon wrote:
> Download
> (link to shady file)

No thanks! Reported and blocked

**Comment by Rawi01** [comment] 2024-09-01 08:07
Duplicate of #3709 

You can use the [PR build artifact](https://github.com/projectlombok/lombok/actions/runs/10479748672?pr=3727) as a temporary workaround.

**Closed by Rawi01** 2024-09-01 08:07 UTC
