### ISSUE TITLE
Can't use ExtensionMethod in Java 8 Interfaces

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#755] opened 2015-07-14 21:55 UTC
_Migrated from Google Code (issue 720)_

**Comment by Rawi01** [comment] 2020-04-27 19:16
@rzwitserloot I just tried to add this feature and it seems like it can be done with a few additional/modified lines. Do you accept a PR for this one?

**Comment by Vyacheslav-Lapin** [comment] 2023-01-12 10:06
is it duplicate of #3228 ?

**Comment by marc-guenther** [comment] 2023-01-19 22:51
Hasn't this been resolved by #3259 last week?

**Closed** 2023-01-20 07:15 UTC
