### ISSUE TITLE
Builder.Default changes NoArgConstrcutor behavior

### ISSUE THREAD

**Issue by scottmboring** [projectlombok/lombok#1424] opened 2017-06-26 23:37 UTC
The Build.Default annotation enables default values when using builder, but those default values are ignored with using the NoArgConstructor.

    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Model {
        @Builder.Default
        private String value1 = "testA";
        private String value2 = "testB";
    }

    @Test
    public void test() {
        final Model model1 = new Model();
        assertNull(model1.value1); // FIXME should not be null
        assertEquals(model1.value2, "testB"); // Correct
        final Model model2 = Model.builder().build();
        assertEquals(model2.value1, "testA"); // Correct
        assertNull(model2.value2); // Correct
    }

**Comment by kevcodez** [comment] 2017-06-28 09:07
See https://github.com/rzwitserloot/lombok/issues/1347

**Comment by rspilker** [comment] 2017-06-29 20:34
See also #1429

**Comment by Rawi01** [comment] 2024-03-12 23:18
Duplicate of #2340

**Closed** 2024-03-12 23:18 UTC
