### ISSUE TITLE
lombok.config ignored when compiling with ecj and maven

### ISSUE THREAD

**Issue by rougou** [projectlombok/lombok#1501] opened 2017-10-23 17:18 UTC
I followed the instructions for [compiling with ecj](https://projectlombok.org/setup/ecj).
The command without maven works and picks up the lombok.config settings, but the maven version seems to ignore them and results in a build error. I discovered this when looking into a similar [issue](https://github.com/groovy/groovy-eclipse/issues/352) I have with groovy-eclipse-compiler.

I'm not sure where the problem lies, but everything works fine in Eclipse IDE so it's disappointing to have the project fail to build via maven.

Thanks.

**Comment by rougou** [comment] 2017-10-24 00:39
Just to ask, are there any arguments or system properties that control recognition of the config file?

**Comment by rspilker** [comment] 2017-10-30 23:02
No, there are no arguments or system properties. I'm working on getting a setup. And example `pom.xml` or `build.grade` that uses ecj would help me reproduce it. So far, I've spent quite some time to get maven compiling with ecj and lombok, and don't get it to work at all.

**Comment by rougou** [comment] 2017-11-01 16:14
Not sure if this is what you're looking for, but I've added some test projects [here](https://github.com/rougou/lomboktest).
groovy-eclipse-noconfig -> Compiles as is.
groovy-eclipse-config -> Fails because lombok.config isn't picked up.
ecj-noconfig -> Compiles, provided jvm args (`-javaagent:path/to/lombok.jar=ECJ`) are set
ecj-config -> Fails because lombok.config isn't picked up.

My pom for the ecj tests are based on the one linked [here ](https://projectlombok.org/setup/ecj) (https://projectlombok.org/files/pom.xml). They use plexus-compiler-eclipse.
I'm not sure what the get-lombok execution is supposed to do though. It doesn't seem to have any effect.

**Comment by rspilker** [comment] 2017-11-29 21:17
For me, the ecj-noconfig didn't compile.

groovy-eclipse-noconfig did work, but groovy-eclipse-config did display an error message, as expected.

**Comment by rspilker** [comment] 2017-11-29 21:18
I'll see if I can first reproduce it with a simpler example that does not use external libraries like Slf4j.

**Comment by wykapedia** [comment] 2018-04-02 19:34
Any updates on this issue?  I have a similar issue where the lombok configurations are not considered from the `lombok.config` file when using groovy-eclipse-compiler.  Here is the maven compile configuration:

```xml
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>2.9.2-01</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.3-01</version>
                    </dependency>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>1.16.18</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <compilerId>groovy-eclipse-compiler</compilerId>
                    <verbose>true</verbose>
                    <fork>true</fork>
                    <compilerArguments>
                        <javaAgentClass>lombok.launch.Agent</javaAgentClass>
                    </compilerArguments>
                </configuration>
            </plugin>
```

**Comment by wykapedia** [comment] 2018-04-04 19:35
Any updates on this issue?  I have a similar issue where the lombok configurations are not considered from the `lombok.config` file when using groovy-eclipse-compiler.  Here is the maven compile configuration:

```xml
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-compiler</artifactId>
                        <version>2.9.2-01</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-eclipse-batch</artifactId>
                        <version>2.4.3-01</version>
                    </dependency>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>1.16.18</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <compilerId>groovy-eclipse-compiler</compilerId>
                    <verbose>true</verbose>
                    <fork>true</fork>
                    <compilerArguments>
                        <javaAgentClass>lombok.launch.Agent</javaAgentClass>
                    </compilerArguments>
                </configuration>
            </plugin>
```

**Comment by wykapedia** [comment] 2018-04-05 20:27
@rspilker have you been able to take a look at this since November?

**Comment by ctippin** [comment] 2018-08-07 14:13
Any update on this issue?

**Comment by philnate** [comment] 2019-09-03 11:27
Is there any update on this @rspilker  ? I found https://stackoverflow.com/a/36715853/1377224 which seems to have helped to read lombok.configs, yet I wasn't able to get it running my groovy tests. I guess I missed something.
Could it be that lombok isn't properly called from the groovy-eclipse-compiler, e.g. that it's having issues resolving the classpath from which it's running? If I see it correctly the classpath is provided with `@some/file`.

**Comment by rspilker** [comment] 2019-09-10 21:13
I do have a problem reproducing the error. I get unrelated errors if I use the example from @wykapedia.

I would love to get a complete pom file that demonstrated the problem. Preferably one I can mount in docker if I use `docker run --rm -it -v /path/to/pom.xml:/workspace/pom.xml lombok-maven-jdk12` where the image is created from `docker build -t lombok-maven-jdk12 -f maven/Dockerfile .` as documented in https://github.com/rzwitserloot/lombok/tree/master/docker/maven

**Comment by Fernal73** [comment] 2020-06-20 04:37
Any progress on this issue? I'd like to use the lombok.config file to set my log variable name to LOGGER but there seems to be no way of specifying the config file via the Lombok maven plugin. Should that be moved to an annotation property instead?

**Comment by mkurz** [comment] 2020-11-09 11:00
> Just to ask, are there any arguments or system properties that control recognition of the config file?

I opened a pull request which adds a system property that allows you to pass a config file, see #2643

**Comment by gsolecki** [comment] 2022-03-25 17:10
Is there any update on this issue?
If this functionality was introduced in Lombok, a lot of projects could use Spock together with Java.

**Comment by rzwitserloot** [comment] 2022-04-17 11:05
@gsolecki That PR from mkurz was used as inspiration for an update, which was applied well over a year ago. If it isn't working for you, then that might be a regression and means I'll pull the code (when I wrote it, I mentioned that it seems really fragile to me. If that is indeed true, the maintenance burden is not worth it). I might be convinced to accept a PR, as leaving it in means we'd be relying on community effort to keep it in working order.

I simply have forgotten to close this issue, it seems.

**Closed by rzwitserloot** 2022-04-17 11:05 UTC
Labels: parked
