### ISSUE TITLE
[BUG] @Builder.Default causes class field initializers not to be executed properly

### ISSUE THREAD

**Issue by mzattera** [projectlombok/lombok#3609] opened 2024-02-19 08:14 UTC
Normally, if a class field has a default value, that default value is assigned to corresponding field BEFORE any constructor is called.
Using @Builder.Default changes this behavior and causes NullPointerExceptions in constructors. This regardless the annotation is used with a class where either @Builder or @SuperBuilder is specified.

The below code throws an exception when executed.

The expectation is that "tasks" field is already initialized to an empty List<> by the time the constructor executes.

Lombok version 1.18.26
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2023-12 (4.30.0)
Build id: 20231201-2043
org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_21.0.1.v20231028-0937

====================

import java.util.ArrayList;
import java.util.List;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.NonNull;

@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Builder
public class Action {

	public static void main(String[] args) {
		new Action(State.NEW, "Hello world.");
	}

	public enum State {
		NEW, FINISHED
	}

	@NonNull
	private State state;

	@NonNull
	@Builder.Default // removing this solves the problem
	private List<String> tasks = new ArrayList<>();

	public Action(@NonNull State state, String task) {
		this.state = state;
		if (task != null)

			// tasks is null at this stage but it should not be
			tasks.add(task);
	}
}

**Comment by Rawi01** [comment] 2024-03-12 23:03
This is a duplicate of https://github.com/projectlombok/lombok/issues/2340

**Closed by Rawi01** 2024-03-12 23:03 UTC
