### ISSUE TITLE
[BUG] Eclipse IDE failed after upgrade to  2021-06 (4.20.0)

### ISSUE THREAD

**Issue by mawtrack** [projectlombok/lombok#2884] opened 2021-06-23 18:00 UTC
**Describe the bug**
Working config with eclipse jave ee develompent +STS failed on start after upgrade to version 2021-06.
Clean install last Eclipse Ide + STS reproduce this error.
After eclipse ide start i get error:
Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2ca9b6d3.

If i deinstall lombok from ide, ide start normaly. Not look methods lombok generated., but started without error. 
On this directory maven build and run work normal. Project build successfuly/

**To Reproduce**
Install  last Eclipse IDE + Lombok.jar

**Expected behavior**
Normal work IDE
Lombok last avalable jy site version 1.18.20

**Additional context**
Error reproduced on upgrade IDE and clean install IDE

**Comment by Rawi01** [comment] 2021-06-23 18:28
Duplicate of #2810

**Closed by Rawi01** 2021-06-23 18:28 UTC
