### ISSUE TITLE
[BUG] Annotation processing fails after lombok because com.sun.tools.javac.comp.Attr#attrib(Env<AttrContext>) fails

### ISSUE THREAD

**Issue by Auties00** [projectlombok/lombok#2907] opened 2021-07-18 16:23 UTC
**Describe the bug**
I'm not completely sure if this is my fault or Lombok's, if it's mine I apologize in advance. I'm writing a custom annotation processor that relies on Sun's Javac API and after some time I've got it to work under all circumstances in a test project. Today I tried to test it in a project that also uses Lombok, but an uncaught compilation error is thrown. This is the important part of the stack trace:
```
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Symbol$MethodSymbol.flags()" because "m" is null
	at jdk.compiler/com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:984)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:893)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribTree(Attr.java:671)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribStat(Attr.java:745)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:5330)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5221)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attribClass(Attr.java:5057)
	at jdk.compiler/com.sun.tools.javac.comp.Attr.attrib(Attr.java:5002)
	at it.auties.reified.simplified.SimpleTypes.resolveEnv(SimpleTypes.java:54)
```

The exception is thrown on line 54 in the SimpleTypes class where I call the method Attr#attrib(Env<AttrContext>) using the environment of the class to parse obtained using Enter#getClassEnv(TypeSymbol). The same exception though isn't thrown if the source files are delomboked before the compilation process starts. This leads me to conclude that Lombok's code generation doesn't apply Symbols to the generated trees causing an exception to be thrown when I try to attribute said trees. If I want my annotations to work alongside Lombok's am I supposed to wait for a particular stage in the compilation process to avoid the attribution process(which as far as I understand is not possible because I also need to generate code) or is there something I'm missing?

Thanks in advance

**Comment by Rawi01** [comment] 2021-07-19 07:20
There were some problems with symbols for generated nodes but they should be fixed if you build lombok yourself using the latest source version. If it still doesn't work please share an example class that triggers this exception.

**Comment by Auties00** [comment] 2021-07-19 15:42
> There were some problems with symbols for generated nodes but they should be fixed if you build lombok yourself using the latest source version. If it still doesn't work please share an example class that triggers this exception.

Isn't the edge release built every night? I'm asking because I'm not that familiar with ant

**Comment by Auties00** [comment] 2021-07-19 19:27
> There were some problems with symbols for generated nodes but they should be fixed if you build lombok yourself using the latest source version. If it still doesn't work please share an example class that triggers this exception.

Okay turns out that compiling the project was super easy. 
Though, even using the version I compiled a similar exception is still being thrown:
```
java.lang.NullPointerException: Cannot read field "name" because "sym" is null
	at jdk.compiler/com.sun.tools.javac.code.Scope$ScopeImpl.enterIfAbsent(Scope.java:490)
	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.getMethodEnv(MemberEnter.java:449)
	at it.auties.reified.simplified.SimpleTypes.findMethodEnv(SimpleTypes.java:93)
	at it.auties.reified.simplified.SimpleClasses.resolveClass(SimpleClasses.java:82)
```
The exception starts from this method:
```
    public Env<AttrContext> getMethodEnv(JCMethodDecl tree, Env<AttrContext> env) {
        Env<AttrContext> mEnv = methodEnv(tree, env);
        mEnv.info.lint = mEnv.info.lint.augment(tree.sym);
        for (List<JCTypeParameter> l = tree.typarams; l.nonEmpty(); l = l.tail)
            mEnv.info.scope.enterIfAbsent(l.head.type.tsym);
        for (List<JCVariableDecl> l = tree.params; l.nonEmpty(); l = l.tail)
            mEnv.info.scope.enterIfAbsent(l.head.sym); // l.head.sym == null but shouldn't
        return mEnv;
    }
```

It looks like @SuperBuilder is responsible for these missing symbols. I use most of the annotations that lombok has to offer and this looks like it's the only one affected by this issue

**Comment by Auties00** [comment] 2021-07-20 14:59
> > There were some problems with symbols for generated nodes but they should be fixed if you build lombok yourself using the latest source version. If it still doesn't work please share an example class that triggers this exception.
> 
> Okay turns out that compiling the project was super easy.
> Though, even using the version I compiled a similar exception is still being thrown:
> 
> ```
> java.lang.NullPointerException: Cannot read field "name" because "sym" is null
> 	at jdk.compiler/com.sun.tools.javac.code.Scope$ScopeImpl.enterIfAbsent(Scope.java:490)
> 	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.getMethodEnv(MemberEnter.java:449)
> 	at it.auties.reified.simplified.SimpleTypes.findMethodEnv(SimpleTypes.java:93)
> 	at it.auties.reified.simplified.SimpleClasses.resolveClass(SimpleClasses.java:82)
> ```
> 
> The exception starts from this method:
> 
> ```
>     public Env<AttrContext> getMethodEnv(JCMethodDecl tree, Env<AttrContext> env) {
>         Env<AttrContext> mEnv = methodEnv(tree, env);
>         mEnv.info.lint = mEnv.info.lint.augment(tree.sym);
>         for (List<JCTypeParameter> l = tree.typarams; l.nonEmpty(); l = l.tail)
>             mEnv.info.scope.enterIfAbsent(l.head.type.tsym);
>         for (List<JCVariableDecl> l = tree.params; l.nonEmpty(); l = l.tail)
>             mEnv.info.scope.enterIfAbsent(l.head.sym); // l.head.sym == null but shouldn't
>         return mEnv;
>     }
> ```
> 
> It looks like @SuperBuilder is responsible for these missing symbols. I use most of the annotations that lombok has to offer and this looks like it's the only one affected by this issue

Update:
I've investigated the issue further today and tried to debug the Javac compiler to be certain that my assumptions were correct. It looks like I was wrong yesterday: the annotation @SuperBuilder is working perfectly. What is not working, though, is the annotation @NonNull if applied to a component if applied to a Record's field.  

Let's consider for example this simple record:
```
record Structure(@NonNull String hello){

}
```
The equivalent in vanilla java would be:

```
record Structure(String hello){
    public Structure(String hello){
        if(hello == null){
           throw new NullPointerException("abc is marked non-null but is null");
        }else {
            this.hello = hello;
        }
    }
}
```

The exception is thrown when MemberEnter tries to determine the environment of the method that encloses the expression `new NullPointerException("abc is marked non-null but is null");`, that is the canonical constructor of the record. As discovered previously, the symbols missing are the parameters'(and potentially type parameters') of the method's argument. This looks to be the issue

**Comment by Auties00** [comment] 2021-07-20 15:09
> > > There were some problems with symbols for generated nodes but they should be fixed if you build lombok yourself using the latest source version. If it still doesn't work please share an example class that triggers this exception.
> > 
> > 
> > Okay turns out that compiling the project was super easy.
> > Though, even using the version I compiled a similar exception is still being thrown:
> > ```
> > java.lang.NullPointerException: Cannot read field "name" because "sym" is null
> > 	at jdk.compiler/com.sun.tools.javac.code.Scope$ScopeImpl.enterIfAbsent(Scope.java:490)
> > 	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.getMethodEnv(MemberEnter.java:449)
> > 	at it.auties.reified.simplified.SimpleTypes.findMethodEnv(SimpleTypes.java:93)
> > 	at it.auties.reified.simplified.SimpleClasses.resolveClass(SimpleClasses.java:82)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The exception starts from this method:
> > ```
> >     public Env<AttrContext> getMethodEnv(JCMethodDecl tree, Env<AttrContext> env) {
> >         Env<AttrContext> mEnv = methodEnv(tree, env);
> >         mEnv.info.lint = mEnv.info.lint.augment(tree.sym);
> >         for (List<JCTypeParameter> l = tree.typarams; l.nonEmpty(); l = l.tail)
> >             mEnv.info.scope.enterIfAbsent(l.head.type.tsym);
> >         for (List<JCVariableDecl> l = tree.params; l.nonEmpty(); l = l.tail)
> >             mEnv.info.scope.enterIfAbsent(l.head.sym); // l.head.sym == null but shouldn't
> >         return mEnv;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It looks like @SuperBuilder is responsible for these missing symbols. I use most of the annotations that lombok has to offer and this looks like it's the only one affected by this issue
> 
> Update:
> I've investigated the issue further today and tried to debug the Javac compiler to be certain that my assumptions were correct. It looks like I was wrong yesterday: the annotation @SuperBuilder is working perfectly. What is not working, though, is the annotation @nonnull if applied to a component if applied to a Record's field.
> 
> Let's consider for example this simple record:
> 
> ```
> record Structure(@NonNull String hello){
> 
> }
> ```
> 
> The equivalent in vanilla java would be:
> 
> ```
> record Structure(String hello){
>     public Structure(String hello){
>         if(hello == null){
>            throw new NullPointerException("abc is marked non-null but is null");
>         }else {
>             this.hello = hello;
>         }
>     }
> }
> ```
> 
> The exception is thrown when MemberEnter tries to determine the environment of the method that encloses the expression `new NullPointerException("abc is marked non-null but is null");`, that is the canonical constructor of the record. As discovered previously, the symbols missing are the parameters'(and potentially type parameters') of the method's argument. This looks to be the issue

Update 2:
It also affects classes

**Comment by Rawi01** [comment] 2021-08-17 06:36
Thanks for all your work, it really helped me to find the actual root cause of this problem. For some reason we always replaced the original paramters of the generated record compact constructor with our own version.

**Comment by Auties00** [comment] 2021-08-17 14:43
> Thanks for all your work, it really helped me to find the actual root cause of this problem. For some reason we always replaced the original paramters of the generated record compact constructor with our own version.

Thanks for fixing the issue. I'm currently on vacation but I'll test it as soon as I'm back

**Closed** 2021-09-16 00:05 UTC
