### ISSUE TITLE
[BUG] Install for Eclipse

### ISSUE THREAD

**Issue by Wern-rm** [projectlombok/lombok#2885] opened 2021-06-23 21:12 UTC
When installing the solution in Eclipse and restarting the environment, I get this error when opening any script.

An error has occurred. See error log for more details. Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module

Java 16
Lombook 1.18.20

Please tell me how to solve this?

**Comment by dabbabi** [comment] 2021-06-23 21:39
@Wern-rm what is the version of eclipse?

**Comment by Rawi01** [comment] 2021-06-23 22:24
Duplicate of #2810

**Closed by Rawi01** 2021-06-23 22:24 UTC
