### ISSUE TITLE
[BUG] Jackson annotation @JsonProperty not working with @Jacksonized

### ISSUE THREAD

**Issue by davidvc** [projectlombok/lombok#2824] opened 2021-04-28 21:44 UTC
**Describe the bug**
If you use the @JsonProperty annotation on a field to provide a property name that differs from the field name, it does not work. This is with Lombok 1.8.2

**To Reproduce**
Here is a sample class and a unit test that fails:
```
  @Value
  @Builder
  @Jacksonized
  private static class JacksonExample {
    @JsonProperty("myName")
    String name;
    int age;
  }

  @Test
  public void jsonPropertyAnnotationLetsYouMapAPropertyToAFieldWithDifferentName() throws Exception {
    JacksonExample jacksonExample = JacksonExample.builder().age(27).name("Joe").build();
    String json = "{\"myName\": \"Joe\", \"age\": 27}";

    ObjectMapper objectMapper = new ObjectMapper();
    JacksonExample result = objectMapper.readValue(json, JacksonExample.class);

    assertThat(result, is(equalTo(jacksonExample)));
  }
```
Here is the error I get: 

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "myName" (class com.ebay.raptor.viexpsvc.common.lombok.LombokExamplesTest$JacksonExample$JacksonExampleBuilder), not marked as ignorable (2 known properties: "name", "age"])
 at [Source: (String)"{"myName": "Joe", "age": 27}"; line: 1, column: 13] (through reference chain: com.ebay.raptor.viexpsvc.common.lombok.LombokExamplesTest$JacksonExample$JacksonExampleBuilder["myName"])
```
When I look at the generated code, the Builder does not have any Jackson annotations on it:

```
    @Generated
    public static class JacksonExampleBuilder {
      @Generated
      private String name;
      @Generated
      private int age;

      @Generated
      JacksonExampleBuilder() {
      }

      @Generated
      public LombokExamplesTest.JacksonExample.JacksonExampleBuilder name(String name) {
        this.name = name;
        return this;
      }

      @Generated
      public LombokExamplesTest.JacksonExample.JacksonExampleBuilder age(int age) {
        this.age = age;
        return this;
      }

      @Generated
      public LombokExamplesTest.JacksonExample build() {
        return new LombokExamplesTest.JacksonExample(this.name, this.age);
      }

      @Generated
      public String toString() {
        return "LombokExamplesTest.JacksonExample.JacksonExampleBuilder(name=" + this.name + ", age=" + this.age + ")";
      }
    }
```

**Expected behavior**
Attaching @JsonProperty to a field should be honored using @Jacksonized with `@Value`

**Version info (please complete the following information):**
 - Lombok version 1.8.2
 - java version 11.
 - 
 ```
openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+2 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+2 (build 11.0.1+13-LTS, mixed mode)
```

**Comment by shengding1214** [comment] 2021-05-13 01:44
It works for me
![image](https://user-images.githubusercontent.com/33724768/118065631-dd758200-b3cf-11eb-9d71-a03bad43d58e.png)

**Comment by P041** [comment] 2022-01-27 19:29
This combination of annotations does not work.

<img width="1341" alt="Screenshot 2022-01-27 at 22 27 18" src="https://user-images.githubusercontent.com/53954926/151429989-b40123b4-1bf4-41bf-bbbd-c90df45e4eca.png">

**Comment by janrieke** [comment] 2022-01-27 20:06
I'm quite sure this has been fixed in the meantime. Can you confirm that this does not work with Lombok 1.18.22?

**Comment by P041** [comment] 2022-01-29 14:33
> I'm quite sure this has been fixed in the meantime. Can you confirm that this does not work with Lombok 1.18.22?

yep, I'm using this version
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
        </dependency>

**Comment by bkuberek** [comment] 2022-03-15 19:32
same here

**Comment by janrieke** [comment] 2022-03-15 22:10
I just checked again, and cannot reproduce. Your example works for me both in Eclipse and javac (via maven compile).
Please double-check that you are actually using the latest version of lombok (also check the version installed in Eclipse, if you are using that IDE).

**Comment by bkuberek** [comment] 2022-03-15 23:45
I am. But I circunvented the issue by renaming the field instead of using `@JsonProperty`. I did not have time to go deeper and I wonder if this could be an Intellij IDEA problem. I experienced this while using Intellij to build. If I have time, I will try reproducing it later.

**Comment by janrieke** [comment] 2022-03-16 10:59
Yes, it could be an IntelliJ IDEA issue. `@Jacksonized` is rather new and experimental, and given that the IntelliJ lombok plugin has its own builder processing, it is very likely that IntelliJ does not (or not correctly) consider this annotation. 

Try building with maven/gradle/whatever you use and check whether the problem persists.

**Comment by rzwitserloot** [comment] 2022-03-16 13:21
I think @janrieke has it right. Without feedback, this can be closed 2022-04-01.

**Comment by sysid** [comment] 2022-11-11 06:34
Same problem for me (1.18.24). Also using Intellij.

**Comment by nucatus** [comment] 2023-05-17 05:02
Make sure that all the jackson annotations are imported from the `com.fasterxml.jackson.annotation` package and NOT from `org.codehaus.jackson.annotate` package. This is a very easy mistake to make.

**Comment by serpmelon** [comment] 2023-09-22 07:24
@nucatus 
You save my ass

**Comment by rzwitserloot** [comment] 2023-09-24 02:08
seems fixed then.

**Closed by rzwitserloot** 2023-09-24 02:08 UTC
Labels: parked
