### ISSUE TITLE
[BUG] Lombok annotation handler class lombok.eclipse.handlers.HandleEqualsAndHashCode failed - See error log.

### ISSUE THREAD

**Issue by navy1978** [projectlombok/lombok#3627] opened 2024-03-15 09:43 UTC
**Describe the bug**
Lombok doest work anymore with the new version of STS: 22.0 
the error I get is this:
Lombok annotation handler class lombok.eclipse.handlers.HandleEqualsAndHashCode failed - See error log.

**To Reproduce**
just import a projects that uses Lombok after having updated the IDE with Lombok

If this is not possible, give us enough to reproduce the problem. If you have stack traces or error messages please include all of them, and include screen shots if that will help explain the problem.

**Version info **
 - Lombok version: 1.18.30 and this one: https://projectlombok.org/download-edge
 - Windows machine with java 21
 -  STS: 22.0

**Comment by robotmonkeylives** [comment] 2024-03-15 13:46
Encountering the same issue with Eclipse 2024-03

**Comment by JanMosigItemis** [comment] 2024-03-15 16:31
I also encountered similar behavior with Eclipse 2024-03 (4.31.0) on Java 17 and 21.

It fails on EqualsAndHashCode, Builder, Constructor, etc. It used to work just fine on Eclipse 2023-12 (4.30).

```
java.lang.NoSuchMethodError: 'java.lang.StringBuffer org.eclipse.jdt.internal.compiler.ast.Expression.print(int, java.lang.StringBuffer)'
	at lombok.eclipse.handlers.EclipseHandlerUtil.createAnnotation(EclipseHandlerUtil.java:1335)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:105)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:265)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:107)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:74)
	at lombok.eclipse.EclipseAST.traverseChildren(EclipseAST.java:231)
	at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:69)
	at lombok.eclipse.EclipseAST.traverse(EclipseAST.java:224)
	at lombok.eclipse.TransformEclipseAST.go(TransformEclipseAST.java:222)
	at lombok.eclipse.TransformEclipseAST.transform(TransformEclipseAST.java:183)
	at lombok.eclipse.TransformEclipseAST.transform_swapped(TransformEclipseAST.java:107)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at lombok.launch.PatchFixesHider$Util.invokeMethod(PatchFixesHider.java:133)
	at lombok.launch.PatchFixesHider$Transform.transform_swapped(PatchFixesHider.java:256)
	at org.eclipse.jdt.internal.compiler.parser.Parser.endParse(Parser.java:11465)
	at org.eclipse.jdt.internal.core.util.CommentRecorderParser.endParse(CommentRecorderParser.java:131)
	at org.eclipse.jdt.internal.compiler.SourceElementParser.endParse(SourceElementParser.java:830)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12666)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12896)
	at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12853)
	at org.eclipse.jdt.internal.compiler.SourceElementParser.parseCompilationUnit(SourceElementParser.java:1122)
	at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:189)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:245)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:585)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:308)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:294)
	at org.eclipse.jdt.internal.core.Openable.isStructureKnown(Openable.java:417)
	at org.sonarlint.eclipse.jdt.internal.JdtUtils.isStructureKnown(JdtUtils.java:88)
	at org.sonarlint.eclipse.jdt.internal.JdtUtils.shouldExclude(JdtUtils.java:83)
	at org.sonarlint.eclipse.jdt.internal.JavaProjectConfiguratorExtension.exclude(JavaProjectConfiguratorExtension.java:95)
	at org.sonarlint.eclipse.core.internal.adapter.DefaultSonarLintAdapterFactory.getFileAdapter(DefaultSonarLintAdapterFactory.java:110)
	at org.sonarlint.eclipse.core.internal.adapter.DefaultSonarLintAdapterFactory.getAdapter(DefaultSonarLintAdapterFactory.java:55)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.lambda$5(AdapterFactoryProxy.java:111)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.eclipse.core.internal.adapter.AdapterFactoryProxy.getAdapter(AdapterFactoryProxy.java:111)
	at org.eclipse.core.internal.runtime.AdapterManager.lambda$7(AdapterManager.java:259)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.eclipse.core.internal.runtime.AdapterManager.getAdapter(AdapterManager.java:272)
	at org.eclipse.core.runtime.PlatformObject.getAdapter(PlatformObject.java:73)
	at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:66)
	at org.eclipse.core.runtime.Adapters.adapt(Adapters.java:115)
	at org.sonarlint.eclipse.core.internal.resources.DefaultSonarLintProjectAdapter$1.visit(DefaultSonarLintProjectAdapter.java:91)
	at org.eclipse.core.internal.resources.Resource.lambda$1(Resource.java:154)
	at org.eclipse.core.internal.resources.Resource.lambda$0(Resource.java:122)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:85)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:90)
	at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:135)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:131)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:92)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:154)
	at org.eclipse.core.internal.resources.Resource.accept(Resource.java:142)
	at org.sonarlint.eclipse.core.internal.resources.DefaultSonarLintProjectAdapter.files(DefaultSonarLintProjectAdapter.java:85)
	at org.sonarlint.eclipse.core.internal.backend.SonarLintEclipseHeadlessRpcClient.listFiles(SonarLintEclipseHeadlessRpcClient.java:66)
	at org.sonarsource.sonarlint.core.rpc.client.SonarLintRpcClientImpl.lambda$listFiles$26(SonarLintRpcClientImpl.java:272)
	at org.sonarsource.sonarlint.core.rpc.client.SonarLintRpcClientImpl.lambda$requestAsync$1(SonarLintRpcClientImpl.java:103)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
eclipse.buildId=4.31.0.20240307-1200
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/<WORKSPACE>
```

**Comment by Rawi01** [comment] 2024-03-15 18:09
Duplicate of #3620

As a workaround you can use lombok.jar linked in the referenced issue.

**Closed by Rawi01** 2024-03-15 18:09 UTC
