### ISSUE TITLE
[BUG] i have 2  similer fields used @data on class only generate a setter method

### ISSUE THREAD

**Issue by 18310781743** [projectlombok/lombok#2949] opened 2021-09-07 03:57 UTC
**Describe the bug**

two fields as eppFloorplanId and eppFloorPlanId 

**To Reproduce**
only generate setEppFloorplanId() method
but toString() and hash() all include over two fileds

**Expected behavior**
generate two setter method setEppFloorplanId() and setEppFloorPlanId()

**Version info (please complete the following information):**
 - Lombok version  1.6.20
 - idea 2021.1.3
 - jdk version 1.8_211

**Additional context**
no other

**Comment by Rawi01** [comment] 2021-09-11 07:55
Duplicate of #2130 and #2693

**Closed by Rawi01** 2021-09-11 07:55 UTC
