### ISSUE TITLE
[BUG?] Problem with @Singular and JDK 17

### ISSUE THREAD

**Issue by cigaly** [projectlombok/lombok#2940] opened 2021-08-25 12:44 UTC
This piece of code is crashing JDK 17 Java compiler. It is not clear if this is bug in Lombok or in JDK 17 ... or in both:

import java.util.Set;

import lombok.Builder;
import lombok.Singular;

@Builder
public class Bug9071263 {

    @Singular
    private Set<String> roles;
}

**Comment by Rawi01** [comment] 2021-08-25 13:03
Most likely a lombok issue, I recently created PR #2936 to add JDK17 support.

**Comment by cigaly** [comment] 2021-08-25 13:34
But still, I would expect from javac to report an error, not to crash.

**Comment by andre161292** [comment] 2021-09-15 07:36
I ran into this issue too and got it working again after removing the `@Singular` annotations. 

Interestingly it worked with the following pre-release version of Java 17 i just installed yesterday:
```
openjdk 17-panama 2021-09-14
OpenJDK Runtime Environment (build 17-panama+3-167)
OpenJDK 64-Bit Server VM (build 17-panama+3-167, mixed mode, sharing)
```

**Comment by rzwitserloot** [comment] 2021-09-15 07:50
Duplicate of #2898

**Closed by rzwitserloot** 2021-09-15 07:50 UTC
