### ISSUE TITLE
[BUG] Eclipse plugin don´t run in eclipse 4.28 (2023/6) 

### ISSUE THREAD

**Issue by pppardo** [projectlombok/lombok#3443] opened 2023-06-30 08:31 UTC
**Describe the bug**
In Eclipse 4.28 Jun 2023, lombok eclipse plugin don´t run after install

**To Reproduce**
Install eclipse plugin and run. In "About Eclipse IDE"->"Installation Details" The Lombok plugin does not appear.

**Expected behavior**
It should work and be detected as a plugin.

**Version info (please complete the following information):**
 - Lombok version Last 1.18.28
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.
 Eclipse 4.28 (2023/6)
 Java: Eclipse\eclipse-jee-2023-06R\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502\jre

**Additional context**

**Comment by janrieke** [comment] 2023-06-30 10:09
That may be an installation issue. Please check whether the path to `lombok.jar` is correct in your `eclipse.ini`.

**Comment by andrehtgti2** [comment] 2023-07-27 12:48
Same here, in Eclipse 4.28 lombok do not work and in Eclipse 4.27 lombok works
Any Solution?

**Comment by dstango** [comment] 2023-07-27 20:36
probably duplicate of https://github.com/projectlombok/lombok/issues/3451 -- see there for a suggested solution to the problem.

Question: how did you install the plugin? Via the lombok installer (with the spicy pepper) or via plugin installation inside of Eclipse? See here for both options: https://projectlombok.org/setup/eclipse

Or did you upgrade Eclipse from e.g. 2023-03 to 2023-06?

**Comment by bvolkmann** [comment] 2023-08-07 12:36
Ok, the solution of #3451 did work for me. Had the same problem with Eclipse 4.28 (2023-6) and the lombok installer.
Moved the lombok jar manually to the eclipse's plugins folder and adapted the eclipse.ini to point at it.

**Comment by rzwitserloot** [comment] 2023-09-14 23:40
I _think_ that commit fixes things. I guess we'll keep this closed as it's kinda hard to test now that you 'fixed' your eclipse, @bvolkmann - but by all means comment here or open a new issue if you run into this again. (NB: edge release doesn't have this commit yet).

**Closed** 2023-09-14 23:39 UTC
