### ISSUE TITLE
[BUG] https://projectlombok.org/edge-releases not available?

### ISSUE THREAD

**Issue by mxmlnglt** [projectlombok/lombok#3414] opened 2023-04-21 11:05 UTC
**Describe the bug**
I'm trying to install the latest (edge) Lombok version in Eclipse due to bug #3332 - as told here:  https://github.com/projectlombok/lombok/issues/3332#issuecomment-1481191303

I then proceeded as explained on [Download 'Edgy Guinea Pig' - the Lombok Cutting Edge build](https://projectlombok.org/download-edge) but to not avail: when entering the repo URL in Eclipse, I get an error message saying this: __Could not find https://projectlombok.org/edge-releases__

Btw going to https://projectlombok.org/edge-releases with a browser shows a blank page with message _This is not the page you're looking for._ and title __Not found__; seems like it's a Cloudflare generated page according to HTML source... so an actual Not Found (404) error?

Same when navigating to https://projectlombok.org/p2 ALTHOUGH I set it up last week (fresh new install at work) and succeeded in installing the regular version of Lombok (1.18.26); must be noted that right now, when I want to _Install New Software..._ in my Eclipse, there is no error for this Repo and it just says "All items are installed" (probably because of some cache I suppose...)

=> might this be related to #3243 (reading several comments which seem to indicate even the regular `/p2` URL was down from time to time...?)

FYI:
```
me@localhost % curl https://projectlombok.org/edge-releases
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Not found</title>
</head>
<body>
	This is not the page you're looking for.
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v52afc6f149f6479b8c77fa569edb01181681764108816" integrity="sha512-jGCTpDpBAYDGNYR5ztKt4BQPGef1P0giN6ZGVUi835kFF88FOmmn8jBQWNgrNd8g/Yu421NdgWhwQoaOPFflDw==" data-cf-beacon='{"rayId":"7bdfd837bf0f0168","version":"2023.3.0","r":1,"b":1,"token":"bdd9b175ea144b3fb1113ff17efe0525","si":100}' crossorigin="anonymous"></script>
</body>
</html>%                                                                                                                                                                                                    ```

**Comment by zeroinformatique** [comment] 2023-04-27 11:13
No issue here, I downloaded the file yesterday and right now.
Make sure you don't have an antivirus or extension filter that blocks the URL, maybe.

**Comment by mxmlnglt** [comment] 2023-04-27 13:11
> No issue here, I downloaded the file yesterday and right now.

How do you actually "downloaded the file"?
If you mean by clicking on the "[Download edge release now!](https://projectlombok.org/lombok-edge.jar)" link, then that's fine for me too...

But I want it downloaded via Repo https://projectlombok.org/edge-releases

**Comment by rzwitserloot** [comment] 2023-09-17 02:43
Odd. I'm pretty sure those existed before and we didn't mess with those settings. We'll look into it.

**Comment by rzwitserloot** [comment] 2023-09-19 22:42
> But I want it downloaded via Repo https://projectlombok.org/edge-releases

That URL is a maven repo and 'go to it with a browser' isn't how you interact with maven repos. Nowhere on the lombok site do we tell you to go here... or do we? If so, please let us know where :)

The place to download the edge if you want to do it manually (and 'I enter this URL in my browser' surely is because you're doing it manually, right?), is [https://projectlombok.org/download-edge](https://projectlombok.org/download-edge) - and you get there by going to the main page, clicking 'download', and then 'edge releases'. As for 'entering that in eclipse', unless that is in some sort of 'enter alternative maven repo root' dialog box, you don't do it that way and I don't think (again if we do let us know where) we tell you to do that.

If you want to install lombok as an eclipse plugin, you go to the eclipse menu, go to Help, Install New Software..., and enter the URL `https://projectlombok.org/p2`. I just tested this and it works fine.

Closing as not reproducible. Comment if I'm missing something.

**Closed by rzwitserloot** 2023-09-19 22:42 UTC
Labels: accepted

**Comment by mxmlnglt** [comment] 2023-10-03 09:25
Hi @rzwitserloot thanks for answering.

> > But I want it downloaded via Repo https://projectlombok.org/edge-releases
> 
> That URL is a maven repo and 'go to it with a browser' isn't how you interact with maven repos. Nowhere on the lombok site do we tell you to go here... or do we? If so, please let us know where :)
> 
> The place to download the edge if you want to do it manually (and 'I enter this URL in my browser' surely is because you're doing it manually, right?), is https://projectlombok.org/download-edge - and you get there by going to the main page, clicking 'download', and then 'edge releases'. As for 'entering that in eclipse', unless that is in some sort of 'enter alternative maven repo root' dialog box, you don't do it that way and I don't think (again if we do let us know where) we tell you to do that.

I didn't mean to "download it with a browser", but have Eclipse itself download the edge release via what is called a "Software Site" (and not a "repo" as I misnamed it).
By following the detailed information on this page https://projectlombok.org/download-edge I thought the URL `https://projectlombok.org/edge-releases` could be used to set a "Software Site" in Eclipse.
Seems it might not be used that way as you called it "a maven repo"...
<img width="410" alt="Screenshot 2023-10-03 at 11 16 28" src="https://github.com/projectlombok/lombok/assets/29626929/63d49ea0-2a6e-49c1-a536-5c0deb971ee6">

Some projects/plugins have dedicated/distinct URLs for "nightly" or "dev" builds e.g. for the Eclipse EGit Mylyn Plugin:
- https://download.eclipse.org/egit/github/updates vs.
- https://download.eclipse.org/egit/github/updates-nightly

> If you want to install lombok as an eclipse plugin, you go to the eclipse menu, go to Help, Install New Software..., and enter the URL `https://projectlombok.org/p2`. I just tested this and it works fine.

I already had this one configured since I started using Lombok plugin in Eclipse (I install it that way actually). But as it's been already described earlier e.g. #3243 this `/p2` repo might be down from time to time. And it doesn't contain the "edge" version.

**Comment by rzwitserloot** [comment] 2023-10-21 09:31
@mxmlnglt That works, but the URL is `https://projectlombok.org/p2`, and is [documented here](https://projectlombok.org/setup/eclipse).

**Comment by mxmlnglt** [comment] 2023-10-25 08:37
> @mxmlnglt That works, but the URL is `https://projectlombok.org/p2`, and is [documented here](https://projectlombok.org/setup/eclipse).

I know (as I explained above) but this doesn't contain the "edge" version (at least the last time I tested it - in April-May 2023).

**Comment by rspilker** [comment] 2023-10-25 08:48
@mxmlnglt that is correct, currently we do not have P2 for edge release, only the maven edge repository and the jar download
