### ISSUE TITLE
[BUG] @SneakyThrows throws a compile error

### ISSUE THREAD

**Issue by RoughlyUnderscore** [projectlombok/lombok#3300] opened 2022-11-17 14:51 UTC
**Describe the bug**
I have recently upgraded my project's Java from 16 to 19. Now, compiling throws an error at a class that has @SneakyThrows - particularly at line 63. Here's my deduction process:
1) I've been getting an empty error ("X:63" with no elaboration); I've changed that line, then outright deleted it, and it still was happening.
2) I cleared the class to only have about 50 lines, then it started throwing an error at the 63rd line of another class.
3) I decided to comment out all the Lombok annotations in both classes and it compiled successfully.
4) I slowly uncommented all the annotations and it compiled successfully, with the exception of @SneakyThrows - in fact, the only 2 classes that had SneakyThrows were the classes that it would throw compile errors at.
As such I've come to a conclusion that something is wrong with the SneakyThrows interpretation, and, for some reason, it's all good in Java 16.
Error: ![image](https://user-images.githubusercontent.com/75266403/202478065-8c5f5e3b-2a76-4633-b767-cde2dc9c8921.png)

**To Reproduce**
Create a project, make a method, in which something would normally throw errors (like IO operations), annotate it with @SneakyThrows, try to compile the project. Make sure that the class has at least 63 lines, preferably more.

**Expected behavior**
The compilation should have been successful even with @SneakyThrows.

**Version info (please complete the following information):**
Lombok:
```xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.24</version>
    <scope>provided</scope>
</dependency>
```
Javac:
```javac 19.0.1```.

**Additional context**
The project is a Spigot plugin.

**Comment by YassinHajaj** [comment] 2022-11-17 22:05
Linked to this ?
https://github.com/projectlombok/lombok/issues/3264

**Comment by pitzzahh** [comment] 2022-11-20 03:02
I also encountered the same error with jdk19.

**Comment by rzwitserloot** [comment] 2023-01-11 23:24
Duplicate of #3264

**Closed by rzwitserloot** 2023-01-11 23:24 UTC
