### ISSUE TITLE
[BUG] handmade no-args constructor drops the default value if the field has `@Builder.Default`

### ISSUE THREAD

**Issue by moznion** [projectlombok/lombok#2854] opened 2021-05-26 05:42 UTC
Hello team,

**Describe the bug**

Once `@Builder` has been used with a handmade no-args constructor (i.e. without `@NoArgsConstructor`) in a special situation, that constructor drops the default value of the field.

**To Reproduce**

```java
import lombok.Builder;

public class Diagnose {
    @Builder
    public static class Foo {
        @Builder.Default
        private String str = "default";

        public Foo() {
        }

        public Foo(final String str) {
            this.str = str;
        }
    }

    public static void main(String... argv) {
        System.out.println(new Foo().str); // `"default"` is the expected value, but it gets `null`
    }
}
```

But if I remove `@Builder.Default` then it can get `"default"` in the main method. And if I use `@NoArgsConstructor` instead of a handmade no-args constructor, it can get the expected default value as well.

[EDIT]
And if I delombok the above code, it works fine though.

**Expected behavior**

I expect it should respect the default value (i.e. `"default"` in the above example) of the field even if I use a handmade no-args constructor with `@Builder` and `@Builder.Default`.

**Version info (please complete the following information):**
 - Lombok version
   - 1.18.20
  
 - Platform
```
$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

---

I'd like to say many thanks for this great project.
regarding,

**Comment by mklueh** [comment] 2021-11-08 14:40
related https://github.com/projectlombok/lombok/issues/2340

**Comment by Rawi01** [comment] 2024-03-12 23:12
Duplicate of #2340

**Closed by Rawi01** 2024-03-12 23:12 UTC
