### ISSUE TITLE
[BUG]  static method not work with Builder.DEFAULT

### ISSUE THREAD

**Issue by jueljust** [projectlombok/lombok#2765] opened 2021-02-28 09:00 UTC
**Describe the bug**
static method not work with Builder.DEFAULT

**To Reproduce**
`
package com.example.annotation;

import lombok.*;
import lombok.experimental.Accessors;
import lombok.extern.java.Log;

import java.util.ArrayList;
import java.util.List;

@floralvikings 
@Data
@Builder
@Value
@RequiredArgsConstructor(staticName = "of")
@EqualsAndHashCode(of="id")
public class LombokDemo {
    @NonNull
    private Integer id;
    @NonNull
    private String name;
    @Builder.Default
    private List<String> list = new ArrayList<String>(){};
    public static void main(String[] args){
        log.info("test");
        LombokDemo a;
        a = LombokDemo.of(1, "a"); //of method not work with Builder.DEFAULT
        System.out.println(a.toString());
        a = LombokDemo.builder().id(1).name("a").build();//builder works
        System.out.println(a.toString());
    }
}
`

**Expected behavior**
`
a = LombokDemo.of(1, "a");
`works and get
`
LombokDemo(id=1, name=a, list=[])
`
**Version info (please complete the following information):**
 - Lombok 1.18.18
 - java 1.8

**Comment by Rawi01** [comment] 2024-03-12 23:05
This is a duplicate of https://github.com/projectlombok/lombok/issues/2340

**Closed by Rawi01** 2024-03-12 23:05 UTC
