### ISSUE TITLE
[BUG] @Builder.Default removes default value when instantiate through constructor

### ISSUE THREAD

**Issue by bioc-peliseda** [projectlombok/lombok#3618] opened 2024-02-29 11:56 UTC
**Describe the bug**
If a class has a field with a default value and it is not set explicitly in a constructor, an instance of that class has the default value when created through that constructor:

```java
@AllArgsConstructor
@Builder
public class FooBar {
    private String foo;
    private String bar = "bar";
    public FooBar(String foo) {
        this.foo = foo;
    }
}
```

```java
FooBar fooBar = new FooBar("foo"); // fooBar.bar is "bar"
```

However, if the field has `@Builder.Default` annotation, it remains `null` when created through the constructor.

**To Reproduce**
```java
@AllArgsConstructor
@Builder
public class FooBar {
    private String foo;
    @Builder.Default
    private String bar = "bar";
    public FooBar(String foo) {
        this.foo = foo;
    }
}
```

```java
FooBar fooBar = new FooBar("foo"); // fooBar.bar is null
```

**Expected behavior**
I'd expect the constructor creates identical objects no matter the `@Builder.Default` annotation.

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - JDK 17.0.10 temurin
 - IntelliJ IDEA 2023.3.3

**Comment by Rawi01** [comment] 2024-03-12 23:02
This is a duplicate of https://github.com/projectlombok/lombok/issues/2340

**Closed by Rawi01** 2024-03-12 23:02 UTC
