### ISSUE TITLE
[FEATURE] Default values for regular methods

### ISSUE THREAD

**Issue by esend7881** [projectlombok/lombok#2903] opened 2021-07-13 21:43 UTC
**Describe the feature**
Could Lombok create an annotation to allow for a default value for regular functions. For example:

```.java
public static void myFunc(String var1, int var2) {
   // code
}

public static void myFunc(String var1) {
   int var2 = 1234;
   // code
}

public static void myFunc(int var2) {
   String var1 = "defaultVal";
   // code
}
```

Could lombok be used so that all I need to do is write:

```.java
public static void myFunc(@Default("defaultVal") String var1, @Default(1234) var2) {
   // code
}
```

I suppose only primitives (int, double, long, etc), object primitives (Integer, Double, Long) and strings could be used here.  Maybe an array of primitives could be done like this `@Default([1, 2, 3, 4])` or `@Default(["my", "string", "array"])`

**Describe the target audience**
This will help in reducing the number of redundant functions for this fairly popular feature that I know is in Python and C++.

**Comment by OneCricketeer** [comment] 2021-11-03 13:40
I personally don't think it's that much effort to write out

```
public static void myFunc(String var1, int var2) {
   // code
}

public static void myFunc(String var1) {
   myFunc(var1, 1234);
}

public static void myFunc(int var2) {
   myFunc("defaultVal", var2);
}
```

**Comment by razbenya** [comment] 2022-01-30 13:22
You may be right when there is 2 parameters, what if there are 3 or 4? 
what if you have like 5 methods with 4 params that each have 3 default in them ? 10 methods will become ~75 methods, almost impossible to overload. 

I am also IN for this feature request.

**Comment by janrieke** [comment] 2022-01-30 16:36
Duplicate of #2316.

**Closed** 2022-01-31 14:41 UTC
