### ISSUE TITLE
[FEATURE] @DefaultValue to set default values when a parameter is null

### ISSUE THREAD

**Issue by datze** [projectlombok/lombok#2874] opened 2021-06-09 05:23 UTC
**Describe the feature**
I suggest a annotation `@DefaultValue(Object)` for constructor/method parameters or even all class members.
It replaces a `null` value with a default value.

Example with boiler-plate code:
```
    public Foo(int value1, String value2, String value3, Integer value4) {
        this.value1 = value1;
        this.value2 = value2 != null ? value2 : "";
        this.value3 = value3 != null ? value3 : "foo";
        this.value4 = value4 != null ? value4 : 45;
    }
```
with Lombok `@DefaulValue()` on the parameters:
```
    public Foo(int value1, @DefaultValue("") String value2, @DefaultValue("foo") String value3, @DefaultValue(45) Integer value4) {
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
        this.value4 = value4;
    }
```

or on the class members
```
class Foo {
    int value1;
    String value2;
    String value3;
    Integer value4;

    public Foo(int value1, String value2, String value3, Integer value4) {
        this.value1 = value1;
        this.value2 = value2 != null ? value2 : "";
        this.value3 = value3 != null ? value3 : "foo";
        this.value4 = value4 != null ? value4 : 45;
    }

    public void setValue1(int value1) {
        this.value1 = value1;
    }

    public void setValue2(String value2) {
        this.value2 = value2 != null ? value2 : "";
    }

    public void setValue3(String value3) {
        this.value3 = value3 != null ? value3 : "foo";
    }

    public void setValue4(Integer value4) {
        this.value4 = value4 != null ? value4 : 45;
    }

}
```
with Lombok:
```
@Setter
@AllArgsConstructor
class Foo {
    int value1;
    @DefaultValue("")
    String value2;
    @DefaultValue("foo")
    String value3;
    @DefaultValue(45)
    Integer value4;
}
```

**Describe the target audience**
There are places where you MUST handle with `null` parameters because you can't change code either because you are not it's owner or it is generated.
In this case you must handle null values and replace them with some default values.

**Additional context**
-

**Comment by janrieke** [comment] 2021-06-09 05:29
Duplicate of #2316.

**Comment by ashimoon** [comment] 2021-06-27 11:24
What about something similar to `Builder.Default`?

```java
@RequiredArgsConstructor(staticName = "create")
private static class ConstructorDefaults {
    @RequiredArgsConstructor.Default
    private final String value = "default-value";
}

```

Generated code:

```java
private static class ConstructorDefaults {
    private final String value;

    public ConstructorDefaults() {
        this("default-value");
    }

    public ConstructorDefaults(final String value) {
        this.value = value;
    }
    
    public static ConstructorDefaults create() {
        return new ConstructorDefaults();
    }
    
    public static ConstructorDefaults create(final String value) {
        return new ConstructorDefaults(value);
    }
}
```

I think this would be awesome! I definitely find myself having to write multiple constructors and static constructors because I want to have defaults. Problem with `Builder` is that it is not clear what is defaultable versus required when building the object.

**Comment by SahanDll** [comment] 2022-04-08 09:19
This will be a great feature to have.

**Comment by rzwitserloot** [comment] 2022-04-17 16:22
The feature is a nebulous cloud of 'something something defaults'. Using `null` as silently meaning: Place replace with a default value is dubious at best, and the followup comment immediately completely abandons this 'null = default' idea and goes with the usual request, namely, default parameter options that result in multiple overloads instead. For which we already have plenty of tickets.

**Closed by rzwitserloot** 2022-04-17 16:22 UTC
