### ISSUE TITLE
[BUG] Eclipse 2021-06 can't integrate lombook

### ISSUE THREAD

**Issue by kervin521** [projectlombok/lombok#2894] opened 2021-07-05 10:48 UTC
**Describe the bug**
before config
![image](https://user-images.githubusercontent.com/9798724/124460431-f4c65f80-ddc1-11eb-90ee-ff495c44ad80.png)
![image](https://user-images.githubusercontent.com/9798724/124460743-538bd900-ddc2-11eb-87c0-aa25ddc8bb12.png)

after config
![image](https://user-images.githubusercontent.com/9798724/124460109-87b2ca00-ddc1-11eb-89d0-7e4a71b9c810.png)
![image](https://user-images.githubusercontent.com/9798724/124460905-8e8e0c80-ddc2-11eb-9b10-8714b62ae8fa.png)

**To Reproduce**
Steps to reproduce the behavior, preferably in the form of the smallest java source file you can make that will show the problem when compiled with `javac -cp lombok.jar ExampleFile.java` or as sole java file in a fresh new eclipse project.

If this is not possible, give us enough to reproduce the problem. If you have stack traces or error messages please include all of them, and include screen shots if that will help explain the problem.

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.
Lombok : 1.18.20
Java :  1.8.0_291
**Additional context**

**Comment by Rawi01** [comment] 2021-07-05 11:46
Duplicate of #2810

**Closed by Rawi01** 2021-07-05 11:46 UTC
