### ISSUE TITLE
[BUG] Cannot run lombok.create-intellij-project.intellij

### ISSUE THREAD

**Issue by dr-carlos** [projectlombok/lombok#3093] opened 2022-01-23 03:46 UTC
**Describe the bug**
I am trying to compile lombok using IntelliJ.
Running the 'lombok.compile.dist' ant task runs with no errors, however trying to run 'lombok.create-intellij-project.intellij' returns the error:
```
/home/me/lombok/buildScripts/create-intellij-project.ant.xml:32: java.lang.IllegalArgumentException: requested configuration not found in projectlombok.org#lombok;working@mycomputer: [ 'buildTools' ]
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:109)
at org.apache.tools.ant.Task.perform(Task.java:350)
at org.apache.tools.ant.Target.execute(Target.java:449)
at org.apache.tools.ant.Target.performTasks(Target.java:470)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
at org.apache.tools.ant.Main.runBuild(Main.java:834)
at org.apache.tools.ant.Main.startAnt(Main.java:223)
...
```

**To Reproduce**
Git clone the lombok repo.
Open IntelliJ and use built-in Ant to run 'lombok.create-intellij-project.intellij'.
The following error appears after downloading ivy and dependencies.

**Expected behavior**
The task should finish without errors.

**Version info (please complete the following information):**
 - Lombok version v1.18.16
 - Platform IntelliJ IDEA 2021.3.1

**Comment by rzwitserloot** [comment] 2022-01-23 09:08
Duplicate of #2860

**Closed by rzwitserloot** 2022-01-23 09:08 UTC
