### ISSUE TITLE
Add support for Java 19

### ISSUE THREAD

**Issue by SimSonic** [projectlombok/lombok#3264] opened 2022-09-22 17:52 UTC
1.18.24:
```
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ soap-clients ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 345 source files to /builds/someproject/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: Error during the transformation of 'somepackage.SomeClass'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 63
[INFO] 1 error
```

I believe there should be just little changes to support new class file version 63.

Thanks.

**Comment by jkickic** [comment] 2022-10-05 08:35
There's a draft PR for this
https://github.com/projectlombok/lombok/pull/3251

**Comment by SimSonic** [comment] 2022-10-05 08:59
> There's a draft PR for this #3251

It's undone and frozen.

**Comment by laxika** [comment] 2022-10-10 09:26
Is the project dead? Or I should send some support money to get this fixed or something? I want to use JDK 19 to be able to use virtual threads, but this unfortunately blocks me entirely. (I use SneakyThrows at 100+ places lol.)

**Comment by alexanderankin** [comment] 2022-10-10 10:19
I am also here because SneakyThrows does not compile on java 19... I think it is worth at least pulling down the branches with the pr's (projectlombok/lombok.patcher#11 and #3251), pushing to maven local and seeing if that works.

i think #3251 is actually doing too much, there should just be a simple pr that bumps the patcher version after pr11 gets merged (if that accomplishes what i think it might, and restore all the base functionality like sneakythrows in java 19)

**Comment by SimSonic** [comment] 2022-10-10 10:19
@rzwitserloot, ping?

**Comment by alexanderankin** [comment] 2022-10-10 10:59
`lombok.extern.slf4j.Slf4j` still works on java 19 as is btw. Another one that is everywhere.

the lombok.patcher pr.11 built and compiled, but it looks like it is an odd version, so that requires making it even for a release (iirc how lombok versioning works, but the version referenced in lombok proper is 44, so I changed `lombok.patcher.Version.VERSION` to "46"). Running `./propagateDistToLombok` script with `./propagateDistToLombok 0.46`, and recompiling lombok -- does not seem to change the version of the patcher which is used in the lombok build.

but after renaming the files manually, and manually creating a pom file, it works! and switching back to the published version (.24), it gives

<details><summary>this error</summary>

```
error: Error during the transformation of 'org.example.Main'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 63
```

</details>

seems like it is just a matter of running the release.

**Comment by Rawi01** [comment] 2022-10-10 11:52
I uploaded a pre-built version of the linked PR: [lombok-jdk19-20221010.zip](https://github.com/projectlombok/lombok/files/9745621/lombok-jdk19-20221010.zip)

It would be really helpful if you can test it with JDK19 and especially some of the new language features. I have no time to do all that myself at the moment.

I know that it is annoying that there is no new release but everyone who works on the project does it in his spare time.

**Comment by alexanderankin** [comment] 2022-10-10 12:13
I've updated my repo to install this new version from @Rawi01 into the maven local repository in alexanderankin/lombok-maven-local-reproducer#1

**Comment by laxika** [comment] 2022-10-15 11:07
@Rawi01 Thanks for the JAR, it works well. I was able to compile the project with it, tests ran just fine and the apps start as expected. I'll do more testing soon but as for now, it looks good!

**Comment by bademux** [comment] 2022-10-30 18:03
@alexanderankin temporary solution
```groovy
task downloadLombok() {
	inputs.property('lombokSrc', 'https://github.com/projectlombok/lombok/files/9745621/lombok-jdk19-20221010.zip')
	outputs.files file("$buildDir/lombok.zip")
	doLast {
		ant.get(src: inputs.properties.lombokSrc, dest: tasks.downloadLombok.outputs.files.singleFile)
	}
}

task installLombok(type: Sync, dependsOn: tasks.downloadLombok) { task ->
	def extractDir = file("${buildDir}/ext-libs")
	outputs.files fileTree(extractDir) {
		include "**/*.jar"
		builtBy task
	}
	from zipTree(tasks.downloadLombok.outputs.files.singleFile)
	into extractDir
}

dependencies {

	compileOnly files({ tasks.installLombok.outputs.files })
	annotationProcessor files({ tasks.installLombok.outputs.files })
}
```

**Comment by Rawi01** [comment] 2022-10-30 18:47
Thanks for testing, I marked my PR as ready

**Comment by stephane-dereppe** [comment] 2022-11-11 08:25
Thanks for the job!

The build of the PR is failing. I guess that's why it is not merged yet.

**Comment by marinus-suniram** [comment] 2022-11-15 13:34
any ETA on this?

**Comment by Harmelodic** [comment] 2022-11-15 14:25
So... we're waiting on this:
- https://github.com/projectlombok/lombok/pull/3251

which is dependent on the lombok patcher being updated, by this:
- https://github.com/projectlombok/lombok.patcher/pull/11

which... doesn't seem to have any blockers.

Waiting on someone with write access to be merge that and kick off things, I guess.

**Comment by Harmelodic** [comment] 2022-11-21 16:19
Update:

To get Java 19 support, this needs to be merged:
- https://github.com/projectlombok/lombok/pull/3251

Which is blocked by the `lombok.patcher` from supporting Java 19/20:
- https://github.com/projectlombok/lombok.patcher/pull/11

Which is blocked/not-wanting-to-merge-yet, because the `lombok.patcher` seems to be in a... weird/broken state, where tags are missing and (maybe) even code is missing:
- https://github.com/projectlombok/lombok.patcher/issues/10

**Comment by laxika** [comment] 2022-12-05 17:55
Any ETA? This one is open for almost 2.5 months. The java release cycle is 6 months so at this pace by the time it will be fixed, JDK 20 will be out already.

I'm using Rawi's jar from a local repo of my project. It works but is still super sketchy, to be honest. :/

**Comment by alexanderankin** [comment] 2022-12-05 18:07
I think its just two maintainers on this project, so i would expect it to be handled at the next lts release, thats about 1.5 years apart.

**Comment by laxika** [comment] 2022-12-05 18:50
> I think its just two maintainers on this project, so i would expect it to be handled at the next lts release, thats about 1.5 years apart.

So I'll need to provide my own patch to jump to JDK 20 in the future? Ouch.

**Comment by MCakrt** [comment] 2022-12-12 17:02
@bademux 
Thank you. I had to tweak it a little bit to make it work in my project:

```
tasks.register('downloadLombok') {
    inputs.property('lombokSrc', 'https://github.com/projectlombok/lombok/files/9745621/lombok-jdk19-20221010.zip')
    outputs.files file("$buildDir/lombok.zip")
    doLast {
        ant.get(src: inputs.properties.lombokSrc, dest: tasks.downloadLombok.outputs.files.singleFile)
    }
}

tasks.register('installLombok', Copy) { task ->
    def extractDir = file("${buildDir}/ext-libs")
    outputs.files fileTree(extractDir) {
        include "**/*.jar"
        builtBy task
    }
    from(zipTree(tasks.downloadLombok.outputs.files.singleFile))
    into extractDir
}

dependencies {

    compileOnly files({ tasks.installLombok.outputs.files })
    annotationProcessor files({ tasks.installLombok.outputs.files })
    testCompileOnly files({ tasks.installLombok.outputs.files })
    testAnnotationProcessor files({ tasks.installLombok.outputs.files })
    
    ...
}

**Comment by laxika** [comment] 2022-12-12 18:50
@MCakrt 

I did something similar, but I committed the JAR into my repo:

`
`

**Comment by bademux** [comment] 2022-12-13 11:04
@laxika
"enterprisy thinking" would be to not use java19 and unofficial lombok in the first place :)

**Comment by laxika** [comment] 2022-12-14 11:24
Damn, you got me!

**Comment by MCakrt** [comment] 2022-12-15 10:18
@laxika That's a good point. I will update my project like this.

**Comment by MCakrt** [comment] 2022-12-20 15:14
@laxika I did it as you suggested. This is much better than pulling stuff from GitHub. Thank you, I am not that familiar with Gradle.

It works well but there's a problem with my IDE (IntelliJ Idea). It doesn't recognize Lombok and highlights all Lombok annotations etc. as errors, even though the code compiles and runs without any problems.

I polished the dependencies further, so now it's
```
    // A forked version of Lombok because the official one doesn't support Java 19 yet
    compileOnly group: 'org.projectlombok', name: 'lombok', version: 'jdk19-20221010'
    annotationProcessor group: 'org.projectlombok', name: 'lombok', version: 'jdk19-20221010'
    testCompileOnly group: 'org.projectlombok', name: 'lombok', version: 'jdk19-20221010'
    testAnnotationProcessor group: 'org.projectlombok', name: 'lombok', version: 'jdk19-20221010'
```

Everything works well now. The code compiles and runs and Idea is happy.

**Comment by laxika** [comment] 2022-12-21 14:39
@MCakrt Do you use the latest IntelliJ Idea? It works for me with the latest one. :/ Nice that you found a fix though!

**Comment by MCakrt** [comment] 2022-12-22 09:52
@laxika I was using the previous version when I wrote the comment. I have upgraded Idea after that.

**Comment by sven-v-t-veer** [comment] 2023-01-06 05:49
> 

I wouldn't commit a jar to my git repository. That's not reallt "enterprise thinking.

Enterprise thinking would be to clone the repo to your enterprise and use git submodules to use lombok in you project.

**Comment by sven-v-t-veer** [comment] 2023-01-06 05:50
> @laxika "enterprisy thinking" would be to not use java19 and unofficial lombok in the first place :)

And why woud that be?

There is a reason why Java updates every 6 months, and there is a reason why every enterprise should too.

**Comment by sven-v-t-veer** [comment] 2023-01-06 05:53
Is there any chance that this support will be added any time soon? I'm considerin de-lomboking my projects over this. Java 19 has been out for months now nd Java 20 will be released within 3 months.

**Comment by laxika** [comment] 2023-01-06 23:43
> Enterprise thinking would be to clone the repo to your enterprise and use git submodules to use lombok in you project.

Actually in an enterprise environment people use their own maven repository. You would fork the lombok repo and deploy your own code into your onw repo.

To be honest, I just ment that line as a joke. It was a crappy one, I see. :)

**Comment by SimSonic** [comment] 2023-01-07 08:47
I think it is not a world-scale problem for us if lombok doesn't update with non lts versions. Actually using non lts is offen considered as risky for enterprise.

But for me it is very dangerous signal that maintainers are silent for months. If the silence will continue after release of java 20, I think somebody should fork repo.

**Comment by rzwitserloot** [comment] 2023-01-12 01:29
@SimSonic wrote:

> I think it is not a world-scale problem for us if lombok doesn't update with non lts versions.

Yup, we didn't feel all that much stress about 19 for that reason.

@alexanderankin wrote:

> so i would expect it to be handled at the next lts release, thats about 1.5 years apart.

Pssh. it's only been 8 months, what's with the hyperbole :)

----

Various awesome PRs - thanks, @Rawi01 :) - have been merged, and JDK19 support has been added.

You can now download [the edge release](https://projectlombok.org/download-edge) and give it a spin! We'll ship this as official release, assuming nobody finds major problems with it, within a week.

Feedback welcome!

**Closed by rzwitserloot** 2023-01-12 01:29 UTC

**Comment by Vyacheslav-Lapin** [comment] 2023-01-12 08:57
Great! Thanks a lot!
But seems like, now we can only download it directly (link https://projectlombok.org/lombok-edge.jar works correctly), but not by Maven or Gradle through remote repository. Got this error while building in my Maven project:

>`[ERROR] Failed to execute goal on project demo-project: Could not resolve dependencies for project demo-project:demo-project:jar:0.0.1-SNAPSHOT: org.projectlombok:lombok:jar:edge-SNAPSHOT was not found in https://projectlombok.org/edge-releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of projectlombok.org has elapsed or updates are forced -> [Help 1]`

**Comment by SimSonic** [comment] 2023-01-12 09:36
+1

![image](https://user-images.githubusercontent.com/2697754/212031141-6c29e595-687b-4a73-910a-c8f0273057c2.png)

**Comment by laxika** [comment] 2023-01-12 09:43
Yaaaay! Thanks a lot for picking this issue up!

**Comment by sz-liva** [comment] 2023-01-12 22:18
It seems like https://projectlombok.org/edge-releases repository doesn't work. I've got this error during Maven build:
> [ERROR] Failed to execute goal on project testproject: Could not resolve dependencies for project com.livalife.api:liva-api:jar:6.1.0-SNAPSHOT: org.projectlombok:lombok:jar:edge-1.18.25 was not found in https://projectlombok.org/edge-releases during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of projectlombok.org has elapsed or updates are forced -> [Help 1]

**Comment by rspilker** [comment] 2023-01-13 01:25
Hmm, possibly the edge release via maven has been broken since we moved the website to a new location.

I know that I'm both maven and grade you can use a local jar, I think you need to mark it `system` for maven.

A fix for the edge release might take another week.

**Comment by rzwitserloot** [comment] 2023-01-20 12:39
Turns out our switch to new hosting is slightly more complex than we signed up for. We'll try to get the release out the door ASAP but would prefer not to kludge it together with a bunch of error-prone manual upload actions.

**Comment by SimSonic** [comment] 2023-01-24 16:41
I suppose this should not be very hard with [their docs for aws cli](https://developers.cloudflare.com/r2/examples/aws-cli/) and [aws cli in docker image](https://hub.docker.com/r/amazon/aws-cli)...

**Comment by sven-v-t-veer** [comment] 2023-01-27 11:40
> I suppose this should not be very hard with [their docs for aws cli](https://developers.cloudflare.com/r2/examples/aws-cli/) and [aws cli in docker image](https://hub.docker.com/r/amazon/aws-cli)...

I'm beginning to think Java 20 might be released first.

**Comment by vananiev** [comment] 2023-02-05 12:36
Thanks a lot, lombok 1.18.26 form mavencentral works correctly with java 19.

**Comment by Harmelodic** [comment] 2023-02-05 17:22
Omg, it's out!
https://mvnrepository.com/artifact/org.projectlombok/lombok/1.18.26

Thanks @rzwitserloot for publishing it!
