### ISSUE TITLE
How to get Lombok work with AspectJ in eclipse?

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#748] opened 2015-07-14 21:55 UTC
_Migrated from Google Code (issue 713)_

**Comment by puel** [comment] 2015-11-20 10:17
Is where any update on this issue? Would be nice to be able to combine both with eclipse.  Using 1.16.6.

**Comment by ahoehma** [comment] 2016-03-12 01:19
I  vote for that :)

**Comment by ivnik** [comment] 2016-07-27 14:17
+1

**Comment by RastaChaum** [comment] 2016-08-24 14:46
+1

**Comment by Nagoo** [comment] 2016-09-02 13:36
In case it could help: Here is the log output I get when the compilation fails:

```
:compileJava
[ant:iajc] <Unknown> [warning] Found @DeclareAnnotation while current release does not support it (see 'org.aspectj.weaver.bcel.AtAjAttributes')
[ant:iajc] 	
[ant:iajc] [warning] You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
[ant:iajc] Your processor is: org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.BatchProcessingEnvImpl
[ant:iajc] Lombok supports: sun/apple javac 1.6, ECJ
[ant:iajc] 	
[ant:iajc] [warning] CAL10NAnnotationProcessor 0.8.1 initialized
[ant:iajc] 	
[ant:iajc] /home/alaza/projects/spring-configurable-demo/src/main/java/com/williewheeler/demos/spring/configurable/web/UserController.java:22 [error] The method getName() is undefined for the type User
[ant:iajc] user.getName();
[ant:iajc]      ^^^^
[ant:iajc] 
[ant:iajc] 1 error, 3 warnings
:compileJava FAILED
```

Is this an Issue that should be fixed in the Lombok project, or in AspectJ?

Let us know if there is any way in which we can help @rzwitserloot.

**Comment by AbdullahAsendar** [comment] 2017-08-14 23:52
+1

**Comment by beihaifeiwu** [comment] 2017-08-15 01:55
+1

**Comment by jchurch33** [comment] 2017-08-29 21:35
+1

**Comment by psehrawa** [comment] 2017-11-05 19:53
+1

**Comment by nimelord** [comment] 2017-12-26 18:40
+1

**Comment by beldon** [comment] 2018-01-05 10:08
+1

**Comment by pucojazu** [comment] 2018-01-05 11:54
+1

**Comment by dptr** [comment] 2018-01-08 07:10
+1

**Comment by BenBK** [comment] 2018-02-12 17:05
+1

**Comment by akabrane** [comment] 2018-02-16 20:31
+1

**Comment by edwinquaihoi** [comment] 2018-03-10 05:00
+1

**Comment by 0r1t0m** [comment] 2018-04-10 06:56
+1

**Comment by jwilmoth** [comment] 2018-04-30 18:09
+1

**Comment by Glowstoner** [comment] 2018-09-16 19:41
+1

**Comment by kajh** [comment] 2019-09-27 09:36
Hi :) Any news abourt this issue? This is a blocker for us regarding beginning to use lombok.

**Comment by rzwitserloot** [comment] 2021-09-12 08:29
Duplicate of #995

**Closed by rzwitserloot** 2021-09-12 08:29 UTC
