### ISSUE TITLE
[BUG] Use of `@FieldNameConstants` generated `Fields` constants in MapStruct's `@Mappings` annotation breaks Java compilation when using several `@Mapping` annotations without wrapping them in a container `@Mappings` annotation

### ISSUE THREAD

**Issue by anno1985** [projectlombok/lombok#2991] opened 2021-10-08 16:19 UTC
**Describe the bug**
I have a class `MyClass` with a property `prop`; the class is annotated with `@FieldNameConstants`.
When I try to use the generated `Fields` class in MapStruct's mapping annotation, for example
```java 
@Mapping(target = MyClass.Fields.prop, ignore = true)
```
then Java's compiler can't find any of Lombok's generated builders anymore (and several, possibly all, other generated items, like loggers):
```
[ERROR] path/to/Another.class[line:pos] cannot find symbol
  symbol:   class AnotherBuilder
  location: class com.example.Another

```
(Note that the errors seem to occur for all classes using Lombok, not just the one with the `@FieldNameConstants` annotation.)

I ensured to use the setup as described in [MapStruct's reference guide](https://mapstruct.org/documentation/stable/reference/html/#_set_up), but with latest stable versions of the three dependencies 
```xml
    <lombok.version>1.18.22</lombok.version>
    <mapstruct.version>1.4.2.Final</mapstruct.version>
    <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
```

I suspect it's down to how the preprocessors are chained, but rearranging the `path` elements in the pom.xml didn't yield any changes in the result.

**Expected behaviour**
Lombok generating the `Fields` class first, then MapStruct running and successfully using the constants, and the build passing. Changing MapStruct's annotation makes it all pass:
```java 
@Mapping(target = "prop", ignore = true)
```

**Comment by anno1985** [comment] 2021-10-11 07:32
Using 1.18.20 doesn't work either - which I assumed is what you meant I give a go...? :)

**Comment by anno1985** [comment] 2021-10-11 08:16
But just to be sure I also compiled 20 times with 1.18.22 - no luck there either

**Comment by anno1985** [comment] 2021-10-11 12:52
I've opened a ticket on MapStruct's tracker as well; cf. above. It contains an example mapper to reproduce the issue.

**Comment by filiphr** [comment] 2021-10-19 19:24
I've had a look at the example from @anno1985. And I do not think that it is related with MapStruct or Lombok, and I think that there is nothing that could be done by either annotation processor about this. 

The compile error we are getting is happening really early in the compilation, even before the annotation processors are run.

The errors I see are:

```
[ERROR] /~/lombok-mapstruct-issue/src/main/java/Mapper.java:[24,29] cannot find symbol
  symbol:   variable Fields
  location: class Entity
[ERROR] /~/lombok-mapstruct-issue/src/main/java/Mapper.java:[25,29] cannot find symbol
  symbol:   variable Fields
  location: class Entity
[ERROR] /~/oss/lombok-mapstruct-issue/src/main/java/Mapper.java:[24,5] expression not allowed as annotation value
```

When I add
```
<compilerArgs>
    <compilerArg>-XprintProcessorInfo</compilerArg>
    <compilerArg>-XprintRounds</compilerArg>
</compilerArgs>
```

to the maven-compiler configuration the processor information is not printed at all. Once I remove the `@Mapping` annotations then I can see

```
[INFO] Compiling 3 source files to /Users/filiphr/development/oss/lombok-mapstruct-issue/target/classes
Round 1:
	input files: {Entity, Dto, Mapper}
	annotations: [lombok.Getter, lombok.Setter, lombok.experimental.FieldNameConstants, lombok.NoArgsConstructor, org.mapstruct.Mapper]
	last round: false
Processor org.mapstruct.ap.MappingProcessor matches [org.mapstruct.Mapper] and returns false.
Processor lombok.launch.AnnotationProcessorHider$AnnotationProcessor matches [lombok.Setter, lombok.Getter, org.mapstruct.Mapper, lombok.experimental.FieldNameConstants, lombok.NoArgsConstructor] and returns false.
Processor lombok.launch.AnnotationProcessorHider$ClaimingProcessor matches [lombok.Setter, lombok.Getter, lombok.experimental.FieldNameConstants, lombok.NoArgsConstructor] and returns true.
Round 2:
	input files: {}
	annotations: []
	last round: false
Processor org.mapstruct.ap.MappingProcessor matches [] and returns false.
Processor lombok.launch.AnnotationProcessorHider$AnnotationProcessor matches [] and returns false.
Processor lombok.launch.AnnotationProcessorHider$ClaimingProcessor matches [] and returns true.
Round 3:
	input files: {}
	annotations: []
	last round: true
```

This makes me believe that the problem is in the fact that at the time of processing the files because they need to be used by the annotation processors the information is just not there and can never be there, since in order to be there one of the processors needs to run. In order to use the fields from Lombok you'll need to do 2 different compilation units. This is not like using classes, since classes have a special way of being marked in the annotation processors that they are not present. However, the `FieldNameConstants` are not like that.

In any case, MapStruct is quite type safe so you can use the strings in the `@Mapping` if something changes MapStruct will have a compile error anyways. If you use the MapStruct IntelliJ plugin you can have refactoring support as well.

@rzwitserloot I hope this analysis helps. If you have some ideas that we could don on the MapStruct side, please let me know. I am happy to help our joint users have a good experience with Lombok and MapStruct.

**Comment by rzwitserloot** [comment] 2021-10-20 01:19
@filiphr fantastic breakdown, thanks!

Yes, this sounds like a chicken-and-egg issue, where lombok just can't "get there fast enough", and javac just locks in that said variable isn't there at the time it needs to be there. The 'rounds' system perhaps isn't up to the job of leaving certain annotations unmentioned and in limbo because they may themselves be generates in another round.

Thus, fixing this would be incredibly difficult / requires a re-design of how lombok works at its core, which may happen someday but for different reasons than this issue. Thus, I think it's best we just close it, unless I'm missing something or someone else wants to invest some time and do more research, in case it's not as dire as I think it is?

**Closed as completed** 2022-03-17 22:26 UTC
Labels: accepted, documentation

**Comment by genglongsir** [comment] 2025-01-25 06:29
> maybe I'm doing something wrong but it doesn't work for me <img alt="Снимок экрана 2022-10-19 в 12 18 53" width="1549" src="https://user-images.githubusercontent.com/40397740/196651083-7ae7be5f-fae1-4f78-b30b-fcdd0cb5dc33.png">
试试这个
https://github.com/mapstruct/mapstruct/issues/2951#issuecomment-2613805761
