### ISSUE TITLE
[BUG] @Builder with Javadoc causes error markers in Java editor with Eclipse 2024-09 (4.33.0)

### ISSUE THREAD

**Issue by meldorq** [projectlombok/lombok#3757] opened 2024-09-27 13:51 UTC
**Describe the bug**

Since the upgrade to Eclipse 2024-09 (4.33) the `@Builder` annotation leads to error markers in the Java editor under special circumstances.

**To Reproduce**

Create a simple maven project in Eclipse containing these two classes:

MyClass.java

```
package test;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class MyClass {

    /**
     * .
     */
    private String name;

}

```
MyClass2.java

```
package test;

public class MyClass2 {

    public void myMethod() {

        MyClass x = MyClass.builder().build();
    }

}
```

The reference to builder() in MyClass2 is underlined red with the error message 'The method builder() is undefined for the type MyClass'

When I remove the Javadoc comment from `name` in MyClass, the error goes away.

**Expected behavior**

There shouldn't be an error.

**Version info (please complete the following information):**
 - Lombok version: 1.18.34
 - Platform: Eclipse 2024-09 (4.33)

**Comment by mduggen** [comment] 2024-10-02 07:55
Also with:
- Lombok version: 1.18.34
- Platform: Eclipse 2024-06 (4.32)

**Comment by cxfly** [comment] 2024-10-10 10:12
Lombok version: 1.18.34
Eclipse Platform	4.33.0.v20240903-0618

There is an error log in the eclipse background, which should be caused by the incompatibility of the new eclipse version.
This can be solved by annotating the type with @NoArgsConstructor @AllArgsConstructor


eclipse error log: 
!MESSAGE Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failed
!STACK 0
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "compilationUnit" is null
	at lombok.eclipse.handlers.EclipseHandlerUtil.setDocComment(EclipseHandlerUtil.java:2841)
	at lombok.eclipse.handlers.EclipseHandlerUtil.setDocComment(EclipseHandlerUtil.java:2830)

**Comment by H-Lo** [comment] 2024-10-11 18:01
I'm joining the error club. Compilation works, but in editor I get red error marks on my builder calls.

**Comment by H-Lo** [comment] 2024-10-11 18:51
If you don't like this error, quick fix is to convert JavaDoc to a normal Java comment:
```
/**
 * Do not use JavaDoc comment style. Or Javadoc, don't know should I use camel case or not.
 */

/*
 * Such a comment does not trigger an error in Eclipse.
 */
```

**Comment by Rawi01** [comment] 2024-10-13 11:10
This issue is a duplicate of #3706 and already fixed. You can use the [latest pipeline build](https://github.com/projectlombok/lombok/actions/runs/11087746762#artifacts) until a new version gets release.

**Closed by Rawi01** 2024-10-13 11:10 UTC
