### ISSUE TITLE
Lombok doesn't work with GWT in hosted mode

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#410] opened 2015-07-14 20:40 UTC
_Migrated from Google Code (issue 337)_

**Comment by nekqy** [comment] 2015-07-28 13:51
Fix of the problem is https://github.com/Xenoage/lombok/ isn't it?

**Comment by rzwitserloot** [comment] 2021-09-14 12:55
Sounds like this was due to a bug in GWT (they mistakenly didn't treat `$` as valid java identifiers), which has since been fixed in GWT, making this bug moot.

**Closed by rzwitserloot** 2021-09-14 12:55 UTC
