### ISSUE TITLE
[BUG] Nested enum causes "@Slf4j is not supported on non-static nested classes" in 1.18.21 and higher

### ISSUE THREAD

**Issue by mricken** [projectlombok/lombok#3069] opened 2021-12-22 20:33 UTC
**Describe the bug**
When using `@Slf4j` on a nested `enum`, I get the following error:

```
/opt/teamcity/work/f09f56b10202e564/java-sdk/bmc-resourcesearch/src/main/java/com/oracle/bmc/resourcesearch/model/QueryableFieldDescription.java:[100,5] @Slf4j is not supported on non-static nested classes.
```

The code is here:
https://github.com/oracle/oci-java-sdk/blob/master/bmc-resourcesearch/src/main/java/com/oracle/bmc/resourcesearch/model/QueryableFieldDescription.java#L100

```
    @lombok.extern.slf4j.Slf4j
    public enum FieldType {
```

This works in `1.18.20` and lower, but breaks on `1.18.21` and `1.18.22`.

**To Reproduce**
Declare a class with a nested `enum` in it. Annotate the nested `enum` with `@Slf4j`.

To reproduce in our codebase, update this property to `1.18.21` or higher.
https://github.com/oracle/oci-java-sdk/blob/master/pom.xml#L42

**Expected behavior**
Since an `enum` is always static, this should compile, just like it did in `1.18.20` and lower.

**Version info (please complete the following information):**
 - Lombok `1.18.21` or higher.
 - `javac 1.8.0_121`
 
**Additional context**
None.

**Comment by Rawi01** [comment] 2021-12-23 11:07
Thanks for the report, this is a duplicate of #2990

**Closed by Rawi01** 2021-12-23 11:07 UTC
