### ISSUE TITLE
Renaming field doesn't rename getters and setters

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#753] opened 2015-07-14 21:55 UTC
_Migrated from Google Code (issue 718)_

**Comment by rgra** [comment] 2015-11-03 18:04
Looks like a duplicate of #210.

**Comment by gregors** [comment] 2017-01-30 15:38
still aggravating in 2017

**Comment by Rawi01** [comment] 2023-11-19 10:51
The issue has been addressed and is [covered by a test](https://github.com/projectlombok/lombok/blob/master/test/eclipse/src/lombok/eclipse/refactoring/RenameTest.java)

**Closed by Rawi01** 2023-11-19 10:51 UTC
