### ISSUE TITLE
[BUG] Kotlin Lombok Getter & Setter Annotations doesn't work

### ISSUE THREAD

**Issue by juferdinand** [projectlombok/lombok#2797] opened 2021-03-29 22:00 UTC
**Describe the bug**
If I use @Getter and @Setter for creating the Getter and Setter, it doesn't works in Kotlin. Kotlin tells me anytime: Kotlin: Cannot access 'id': it is private in 'Users'

Is an fix planned?

**To Reproduce**
Creating an Kotlin Project, creating an Entityclass and add @Getter & @Setter Annotation and some private variables. Now create other Class where you try to access the Variables (In Kotlin works like this: users.id)

**Expected behavior**
I had want that the variables can be reached over getter and setter and this shoudl created with @Getter and @Setter

**Version info (please complete the following information):**
 - edge-SNAPSHOT 
 - I use IntelliJ, Kotlin version 1.5.0-M2 and JDK 15

**Additional context**
If you need more Informations just quest :)

**Comment by yukihane** [comment] 2022-01-04 11:43
Following issue may be related:
- [KT-50013 Mixed Java-Kotlin Project with Lombok annotations on Java classes fails to compile.](https://youtrack.jetbrains.com/issue/KT-50013)

**Comment by rzwitserloot** [comment] 2022-01-23 09:11
I'm pretty sure `kotlinc` does not execute annotation processors at all, meaning, it's their bug, not ours, _and_ they probably consider it a feature, so, good luck. That was the problem many moons ago. I don't know what it is now, but we're never going to pick this up on our own; we do not use kotlin. Somebody needs to do the legwork to even get an idea about what we could do to fix it, create a script of source that reproduces an error that we can attempt to make go away, and so on. No promises; if that exists, we'll still need to find some time to look at it, but without it, I don't see us getting to it.

**Comment by rzwitserloot** [comment] 2022-01-23 12:11
Duplicate of #1169

**Closed by rzwitserloot** 2022-01-23 12:11 UTC
