### ISSUE TITLE
[BUG] lombok.config file not taken in account on Eclipse 2023-03 fresh install

### ISSUE THREAD

**Issue by isardds** [projectlombok/lombok#3380] opened 2023-03-23 13:54 UTC
All in the title.

What I do :

* download a fresh java web developer zip file from the Eclipse official website
* installation of Lombok version 1.18.26
* start Eclipse
* create a new maven project
* create a new classe
* add `@Log` annotation on class
* in a method call `log.warning("test");` => works fine
* create a lombok.config file at the project root folder (near pom.xml)
* add key : `lombok.log.fieldName=LOGGER`
* save file

The class continue to compile instead of throw a compilation error. And, if I write `LOGGER.warning("test")`, Eclipse indicates a compilation error, the variable does not exist.

If the done the same thing with Eclipse 2022-12, all works file, the lombok.config file is correctly taken in account and the variable LOGGER is accepted.

Someone have any idea about this issue?

Thanks a lot for your help.

**Comment by isardds** [comment] 2023-03-23 14:01
Additional information, the is no information in the `Error log` view of Eclipse.

**Comment by Rawi01** [comment] 2023-03-23 17:38
This is a duplicate of  #3332 and fixed in the [edge release](https://projectlombok.org/download-edge).

**Closed by Rawi01** 2023-03-23 17:38 UTC
