### ISSUE TITLE
[BUG] @Builder.Default causes fields to be uninitialised when constructor is called

### ISSUE THREAD

**Issue by mprowaznik** [projectlombok/lombok#3385] opened 2023-03-27 15:39 UTC
**Describe the bug**
Following test does not pass:
```

import lombok.AllArgsConstructor;
import lombok.Builder;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class BuilderDefaultTest {
    @Builder
    @AllArgsConstructor
    public static class A {
        @Builder.Default
        int x = 1;
        @Builder.Default
        int y = 1;

        public A(int x) {
            this.x = x;
        }
    }

    @AllArgsConstructor
    public static class B {
        int x = 1;
        int y = 1;

        public B(int x) {
            this.x = x;
        }
    }


    @Test
    public void testA() {
        A a = new A(3);
        assertThat(a.y).isEqualTo(1);
    }

    @Test
    public void testB() {
        B b = new B(3);
        assertThat(b.y).isEqualTo(1);
    }
}
```
Result:
```
org.opentest4j.AssertionFailedError: 
expected: 1
 but was: 0
```

**To Reproduce**

Execute test in previous step.

**Expected behavior**
Field `y` of `A a` object should be initialised, like in object `B b`

**Version info (please complete the following information):**
 - Lombok version: 1.18.24
 - Platform:
 ```
openjdk version "17.0.4" 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)
```

**Comment by Rawi01** [comment] 2023-04-16 13:12
This is a duplicate of #2340

**Closed by Rawi01** 2023-04-16 13:12 UTC
